// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package dbqueries

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type EventLevel string

const (
	EventLevelInfo     EventLevel = "info"
	EventLevelWarn     EventLevel = "warn"
	EventLevelError    EventLevel = "error"
	EventLevelCritical EventLevel = "critical"
)

func (e *EventLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventLevel(s)
	case string:
		*e = EventLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for EventLevel: %T", src)
	}
	return nil
}

type NullEventLevel struct {
	EventLevel EventLevel
	Valid      bool // Valid is true if EventLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventLevel) Scan(value interface{}) error {
	if value == nil {
		ns.EventLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventLevel), nil
}

type EventResult string

const (
	EventResultSuccess EventResult = "success"
	EventResultNone    EventResult = "none"
	EventResultFailure EventResult = "failure"
)

func (e *EventResult) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventResult(s)
	case string:
		*e = EventResult(s)
	default:
		return fmt.Errorf("unsupported scan type for EventResult: %T", src)
	}
	return nil
}

type NullEventResult struct {
	EventResult EventResult
	Valid       bool // Valid is true if EventResult is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventResult) Scan(value interface{}) error {
	if value == nil {
		ns.EventResult, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventResult.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventResult) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventResult), nil
}

type MaintenanceScope string

const (
	MaintenanceScopeAll      MaintenanceScope = "all"
	MaintenanceScopeAuth     MaintenanceScope = "auth"
	MaintenanceScopeProjects MaintenanceScope = "projects"
)

func (e *MaintenanceScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MaintenanceScope(s)
	case string:
		*e = MaintenanceScope(s)
	default:
		return fmt.Errorf("unsupported scan type for MaintenanceScope: %T", src)
	}
	return nil
}

type NullMaintenanceScope struct {
	MaintenanceScope MaintenanceScope
	Valid            bool // Valid is true if MaintenanceScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMaintenanceScope) Scan(value interface{}) error {
	if value == nil {
		ns.MaintenanceScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MaintenanceScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMaintenanceScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MaintenanceScope), nil
}

type MaintenanceStatus string

const (
	MaintenanceStatusScheduled  MaintenanceStatus = "scheduled"
	MaintenanceStatusInprogress MaintenanceStatus = "in progress"
	MaintenanceStatusCompleted  MaintenanceStatus = "completed"
)

func (e *MaintenanceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MaintenanceStatus(s)
	case string:
		*e = MaintenanceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MaintenanceStatus: %T", src)
	}
	return nil
}

type NullMaintenanceStatus struct {
	MaintenanceStatus MaintenanceStatus
	Valid             bool // Valid is true if MaintenanceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMaintenanceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MaintenanceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MaintenanceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMaintenanceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MaintenanceStatus), nil
}

type MaintenanceType string

const (
	MaintenanceTypeEmergency MaintenanceType = "emergency"
	MaintenanceTypePlanned   MaintenanceType = "planned"
)

func (e *MaintenanceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MaintenanceType(s)
	case string:
		*e = MaintenanceType(s)
	default:
		return fmt.Errorf("unsupported scan type for MaintenanceType: %T", src)
	}
	return nil
}

type NullMaintenanceType struct {
	MaintenanceType MaintenanceType
	Valid           bool // Valid is true if MaintenanceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMaintenanceType) Scan(value interface{}) error {
	if value == nil {
		ns.MaintenanceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MaintenanceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMaintenanceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MaintenanceType), nil
}

type NotificationScope string

const (
	NotificationScopeUser      NotificationScope = "user"
	NotificationScopeBroadcast NotificationScope = "broadcast"
	NotificationScopeSegment   NotificationScope = "segment"
)

func (e *NotificationScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationScope(s)
	case string:
		*e = NotificationScope(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationScope: %T", src)
	}
	return nil
}

type NullNotificationScope struct {
	NotificationScope NotificationScope
	Valid             bool // Valid is true if NotificationScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationScope) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationScope), nil
}

type OauthServiceEnum string

const (
	OauthServiceEnumVk OauthServiceEnum = "vk"
)

func (e *OauthServiceEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OauthServiceEnum(s)
	case string:
		*e = OauthServiceEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for OauthServiceEnum: %T", src)
	}
	return nil
}

type NullOauthServiceEnum struct {
	OauthServiceEnum OauthServiceEnum
	Valid            bool // Valid is true if OauthServiceEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOauthServiceEnum) Scan(value interface{}) error {
	if value == nil {
		ns.OauthServiceEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OauthServiceEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOauthServiceEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OauthServiceEnum), nil
}

type PictureOwnerType string

const (
	PictureOwnerTypeUser        PictureOwnerType = "user"
	PictureOwnerTypeProject     PictureOwnerType = "project"
	PictureOwnerTypeUnspecified PictureOwnerType = "unspecified"
)

func (e *PictureOwnerType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PictureOwnerType(s)
	case string:
		*e = PictureOwnerType(s)
	default:
		return fmt.Errorf("unsupported scan type for PictureOwnerType: %T", src)
	}
	return nil
}

type NullPictureOwnerType struct {
	PictureOwnerType PictureOwnerType
	Valid            bool // Valid is true if PictureOwnerType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPictureOwnerType) Scan(value interface{}) error {
	if value == nil {
		ns.PictureOwnerType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PictureOwnerType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPictureOwnerType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PictureOwnerType), nil
}

type PictureRateState string

const (
	PictureRateStateGood    PictureRateState = "good"
	PictureRateStateBad     PictureRateState = "bad"
	PictureRateStateNeutral PictureRateState = "neutral"
)

func (e *PictureRateState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PictureRateState(s)
	case string:
		*e = PictureRateState(s)
	default:
		return fmt.Errorf("unsupported scan type for PictureRateState: %T", src)
	}
	return nil
}

type NullPictureRateState struct {
	PictureRateState PictureRateState
	Valid            bool // Valid is true if PictureRateState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPictureRateState) Scan(value interface{}) error {
	if value == nil {
		ns.PictureRateState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PictureRateState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPictureRateState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PictureRateState), nil
}

type ProjectCategories string

const (
	ProjectCategoriesValue0 ProjectCategories = "благоустройство"
	ProjectCategoriesValue1 ProjectCategories = "дороги и тротуары"
	ProjectCategoriesValue2 ProjectCategories = "освещение"
	ProjectCategoriesValue3 ProjectCategories = "детские площадки"
	ProjectCategoriesValue4 ProjectCategories = "парки и скверы"
	ProjectCategoriesValue5 ProjectCategories = "другое"
)

func (e *ProjectCategories) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProjectCategories(s)
	case string:
		*e = ProjectCategories(s)
	default:
		return fmt.Errorf("unsupported scan type for ProjectCategories: %T", src)
	}
	return nil
}

type NullProjectCategories struct {
	ProjectCategories ProjectCategories
	Valid             bool // Valid is true if ProjectCategories is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProjectCategories) Scan(value interface{}) error {
	if value == nil {
		ns.ProjectCategories, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProjectCategories.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProjectCategories) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProjectCategories), nil
}

type ProjectVoteStatus string

const (
	ProjectVoteStatusArchived       ProjectVoteStatus = "archived"
	ProjectVoteStatusImplementing   ProjectVoteStatus = "implementing"
	ProjectVoteStatusVoteinprogress ProjectVoteStatus = "vote in progress"
	ProjectVoteStatusClosed         ProjectVoteStatus = "closed"
	ProjectVoteStatusPublished      ProjectVoteStatus = "published"
	ProjectVoteStatusInmoderation   ProjectVoteStatus = "in moderation"
)

func (e *ProjectVoteStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProjectVoteStatus(s)
	case string:
		*e = ProjectVoteStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProjectVoteStatus: %T", src)
	}
	return nil
}

type NullProjectVoteStatus struct {
	ProjectVoteStatus ProjectVoteStatus
	Valid             bool // Valid is true if ProjectVoteStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProjectVoteStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProjectVoteStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProjectVoteStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProjectVoteStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProjectVoteStatus), nil
}

type SubmissionsState string

const (
	SubmissionsStateApproved SubmissionsState = "approved"
	SubmissionsStateDeclined SubmissionsState = "declined"
	SubmissionsStateWaiting  SubmissionsState = "waiting"
)

func (e *SubmissionsState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubmissionsState(s)
	case string:
		*e = SubmissionsState(s)
	default:
		return fmt.Errorf("unsupported scan type for SubmissionsState: %T", src)
	}
	return nil
}

type NullSubmissionsState struct {
	SubmissionsState SubmissionsState
	Valid            bool // Valid is true if SubmissionsState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubmissionsState) Scan(value interface{}) error {
	if value == nil {
		ns.SubmissionsState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubmissionsState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubmissionsState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubmissionsState), nil
}

type TicketCloseBy string

const (
	TicketCloseByUser   TicketCloseBy = "user"
	TicketCloseByStaff  TicketCloseBy = "staff"
	TicketCloseBySystem TicketCloseBy = "system"
)

func (e *TicketCloseBy) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketCloseBy(s)
	case string:
		*e = TicketCloseBy(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketCloseBy: %T", src)
	}
	return nil
}

type NullTicketCloseBy struct {
	TicketCloseBy TicketCloseBy
	Valid         bool // Valid is true if TicketCloseBy is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketCloseBy) Scan(value interface{}) error {
	if value == nil {
		ns.TicketCloseBy, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketCloseBy.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketCloseBy) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketCloseBy), nil
}

type TicketMessageAuthor string

const (
	TicketMessageAuthorUser   TicketMessageAuthor = "user"
	TicketMessageAuthorStaff  TicketMessageAuthor = "staff"
	TicketMessageAuthorSystem TicketMessageAuthor = "system"
)

func (e *TicketMessageAuthor) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketMessageAuthor(s)
	case string:
		*e = TicketMessageAuthor(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketMessageAuthor: %T", src)
	}
	return nil
}

type NullTicketMessageAuthor struct {
	TicketMessageAuthor TicketMessageAuthor
	Valid               bool // Valid is true if TicketMessageAuthor is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketMessageAuthor) Scan(value interface{}) error {
	if value == nil {
		ns.TicketMessageAuthor, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketMessageAuthor.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketMessageAuthor) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketMessageAuthor), nil
}

type TicketStatus string

const (
	TicketStatusValue0 TicketStatus = "в обработке"
	TicketStatusValue1 TicketStatus = "закрыт"
	TicketStatusValue2 TicketStatus = "ожидает"
)

func (e *TicketStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketStatus(s)
	case string:
		*e = TicketStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketStatus: %T", src)
	}
	return nil
}

type NullTicketStatus struct {
	TicketStatus TicketStatus
	Valid        bool // Valid is true if TicketStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TicketStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketStatus), nil
}

type TicketTopic string

const (
	TicketTopicValue0 TicketTopic = "аккаунт и доступ"
	TicketTopicValue1 TicketTopic = "проект и заявка"
	TicketTopicValue2 TicketTopic = "техническая проблема"
	TicketTopicValue3 TicketTopic = "другое"
)

func (e *TicketTopic) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketTopic(s)
	case string:
		*e = TicketTopic(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketTopic: %T", src)
	}
	return nil
}

type NullTicketTopic struct {
	TicketTopic TicketTopic
	Valid       bool // Valid is true if TicketTopic is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketTopic) Scan(value interface{}) error {
	if value == nil {
		ns.TicketTopic, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketTopic.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketTopic) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketTopic), nil
}

type VerificationPurpose string

const (
	VerificationPurposeVerifyEmail   VerificationPurpose = "verify_email"
	VerificationPurposeResetPassword VerificationPurpose = "reset_password"
	VerificationPurposeResetTotp     VerificationPurpose = "reset_totp"
)

func (e *VerificationPurpose) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VerificationPurpose(s)
	case string:
		*e = VerificationPurpose(s)
	default:
		return fmt.Errorf("unsupported scan type for VerificationPurpose: %T", src)
	}
	return nil
}

type NullVerificationPurpose struct {
	VerificationPurpose VerificationPurpose
	Valid               bool // Valid is true if VerificationPurpose is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVerificationPurpose) Scan(value interface{}) error {
	if value == nil {
		ns.VerificationPurpose, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VerificationPurpose.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVerificationPurpose) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VerificationPurpose), nil
}

type AuthActionToken struct {
	ID        int64
	Email     string
	Purpose   VerificationPurpose
	TokenHash []byte
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	Ip        *netip.Addr
	UserAgent pgtype.Text
}

type Ban struct {
	ID       pgtype.UUID
	Executor int64
	Target   int64
	Reason   pgtype.Text
	At       pgtype.Timestamptz
	Expires  pgtype.Timestamptz
}

type BannedEmail struct {
	ID        int64
	Email     string
	Reason    string
	CreatedAt pgtype.Timestamptz
}

type Event struct {
	ID        pgtype.UUID
	At        pgtype.Timestamptz
	EventType string
	Level     EventLevel
	Message   pgtype.Text
	ActorType string
	ActorID   pgtype.Int8
	TraceID   string
	Result    string
}

type Maintenance struct {
	ID             pgtype.UUID
	Description    string
	Status         MaintenanceStatus
	Scope          MaintenanceScope
	Type           MaintenanceType
	PlannedStartAt pgtype.Timestamptz
	PlannedEndAt   pgtype.Timestamptz
	ActualStartAt  pgtype.Timestamptz
	ActualEndAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	CalledBy       int64
}

type Notification struct {
	ID            pgtype.UUID
	Body          string
	Createdat     pgtype.Timestamptz
	Scope         NotificationScope
	Targetuserid  pgtype.Int8
	Targetsegment pgtype.Text
	Expiresat     pgtype.Timestamptz
}

type NotificationReceipt struct {
	NotifyID pgtype.UUID
	Userid   int64
	Readat   pgtype.Timestamptz
}

type Oauth struct {
	Uid      int64
	Service  OauthServiceEnum
	LinkedID string
	At       pgtype.Timestamptz
}

type Picture struct {
	ID        pgtype.UUID
	Owner     string
	OwnerType PictureOwnerType
	Info      sql.NullString
	Rate      PictureRateState
	At        pgtype.Timestamptz
}

type Project struct {
	ID         pgtype.UUID
	AuthorUid  int64
	Info       string
	Status     ProjectVoteStatus
	LikesCount int32
	CreatedAt  pgtype.Timestamptz
}

type ProjectLike struct {
	ProjectID pgtype.UUID
	UserUid   int64
	CreatedAt pgtype.Timestamptz
}

type ProjectMessage struct {
	ID        int64
	ProjectID pgtype.UUID
	AuthorUid int64
	Content   string
	ReplyToID pgtype.Int8
	At        pgtype.Timestamptz
}

type ProjectPhoto struct {
	ID          pgtype.UUID
	ProjectID   pgtype.UUID
	ObjectKey   string
	ContentType pgtype.Text
	SizeBytes   pgtype.Int8
	CreatedAt   pgtype.Timestamptz
}

type Rank struct {
	Name        string
	Color       int32
	Description string
	Weight      int32
	Permissions string
	AddedAt     pgtype.Timestamptz
}

type RankActivation struct {
	ID          pgtype.UUID
	Code        pgtype.UUID
	Rank        string
	Createdat   pgtype.Timestamptz
	Activated   pgtype.Timestamptz
	ActivatedBy pgtype.Int8
}

type SeedCredential struct {
	Username  string
	Email     string
	Password  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Session struct {
	ID            pgtype.UUID
	Uid           int64
	CreatedAt     pgtype.Timestamptz
	LastSeenAt    pgtype.Timestamptz
	Expires       pgtype.Timestamptz
	Revoked       bool
	MfaComplete   bool
	UserAgentHash string
}

type StatisticsRecap struct {
	ID         pgtype.UUID
	At         pgtype.Timestamptz
	UsActivity string
	NewIdeas   int64
	VoteCount  int64
}

type Submission struct {
	ID        int64
	ProjectID pgtype.UUID
	State     SubmissionsState
	Reason    pgtype.Text
}

type Ticket struct {
	ID             pgtype.UUID
	Name           pgtype.Text
	Email          pgtype.Text
	Authorized     bool
	AuthorizedUid  pgtype.Int8
	RequestorToken pgtype.Text
	Count          int64
	Acceptor       pgtype.Int8
	Status         TicketStatus
	Topic          TicketTopic
	Brief          string
	Created        pgtype.Timestamptz
	Accepted       pgtype.Timestamptz
	Closed         pgtype.Timestamptz
	ClosedBy       NullTicketCloseBy
	CloseReason    pgtype.Text
}

type TicketMessage struct {
	ID          int64
	Ticket      pgtype.UUID
	AuthorType  TicketMessageAuthor
	AuthorUid   pgtype.Int8
	AuthorName  pgtype.Text
	AuthorEmail pgtype.Text
	Content     string
	At          pgtype.Timestamptz
	EditedAt    pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	DeletedBy   pgtype.Int8
}

type User struct {
	Uid                  int64
	Username             string
	Email                string
	Settings             string
	Rank                 string
	Permissions          string
	Joined               pgtype.Timestamptz
	Password             pgtype.Text
	TotpEnabled          bool
	TotpSecret           pgtype.Text
	TotpPendingSecret    pgtype.Text
	TotpConfirmedAt      pgtype.Timestamptz
	TotpLastStep         pgtype.Int8
	TotpPendingCreatedAt pgtype.Timestamptz
}

type UserAvatar struct {
	UserID      int64
	ObjectKey   string
	ContentType pgtype.Text
	SizeBytes   pgtype.Int8
	UpdatedAt   pgtype.Timestamptz
}

type UsersRecoveryCode struct {
	UserID    int64
	CodeHash  string
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}
