// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: repo.sql

package dbqueries

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const GetProject1 = `-- name: GetProject1 :one
SELECT p.id, p.author_uid, (p.info).title, (p.info).description, (p.info).category, ((p.info).location).city, ((p.info).location).latitude, ((p.info).location).longitude, ((p.info).location).address, p.likes_count, p.created_at, p.status FROM projects p WHERE p.id = $1
`

type GetProject1Row struct {
	ID         pgtype.UUID
	AuthorUid  int64
	Column3    interface{}
	Column4    interface{}
	Column5    interface{}
	Column6    interface{}
	Column7    interface{}
	Column8    interface{}
	Column9    interface{}
	LikesCount int32
	CreatedAt  pgtype.Timestamptz
	Status     ProjectVoteStatus
}

func (q *Queries) GetProject1(ctx context.Context, id pgtype.UUID) (GetProject1Row, error) {
	row := q.db.QueryRow(ctx, GetProject1, id)
	var i GetProject1Row
	err := row.Scan(
		&i.ID,
		&i.AuthorUid,
		&i.Column3,
		&i.Column4,
		&i.Column5,
		&i.Column6,
		&i.Column7,
		&i.Column8,
		&i.Column9,
		&i.LikesCount,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const GetProjectPhotos1 = `-- name: GetProjectPhotos1 :many
SELECT p.object_key, p.content_type, p.size_bytes, p.created_at
		FROM project_photos p
		WHERE p.project_id = $1
		ORDER BY p.created_at
`

type GetProjectPhotos1Row struct {
	ObjectKey   string
	ContentType pgtype.Text
	SizeBytes   pgtype.Int8
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) GetProjectPhotos1(ctx context.Context, projectID pgtype.UUID) ([]GetProjectPhotos1Row, error) {
	rows, err := q.db.Query(ctx, GetProjectPhotos1, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProjectPhotos1Row
	for rows.Next() {
		var i GetProjectPhotos1Row
		if err := rows.Scan(
			&i.ObjectKey,
			&i.ContentType,
			&i.SizeBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetWhoLikedProject1 = `-- name: GetWhoLikedProject1 :many
SELECT u.uid, u.username, u.email, u.settings, u.rank, u.permissions, u.joined, u.password, u.totp_enabled, u.totp_secret, u.totp_pending_secret, u.totp_confirmed_at, u.totp_last_step, u.totp_pending_created_at FROM project_likes l JOIN users u ON u.uid = l.user_uid WHERE l.project_id = $1 ORDER BY l.created_at DESC OFFSET $2
`

type GetWhoLikedProject1Params struct {
	ProjectID pgtype.UUID
	Offset    int32
}

func (q *Queries) GetWhoLikedProject1(ctx context.Context, arg GetWhoLikedProject1Params) ([]User, error) {
	rows, err := q.db.Query(ctx, GetWhoLikedProject1, arg.ProjectID, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Uid,
			&i.Username,
			&i.Email,
			&i.Settings,
			&i.Rank,
			&i.Permissions,
			&i.Joined,
			&i.Password,
			&i.TotpEnabled,
			&i.TotpSecret,
			&i.TotpPendingSecret,
			&i.TotpConfirmedAt,
			&i.TotpLastStep,
			&i.TotpPendingCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const LoggerRepositoryAppend1 = `-- name: LoggerRepositoryAppend1 :exec
INSERT INTO events(event_type, level, message, actor_type, actor_id, trace_id, result) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type LoggerRepositoryAppend1Params struct {
	EventType string
	Level     EventLevel
	Message   pgtype.Text
	ActorType string
	ActorID   pgtype.Int8
	TraceID   string
	Result    string
}

func (q *Queries) LoggerRepositoryAppend1(ctx context.Context, arg LoggerRepositoryAppend1Params) error {
	_, err := q.db.Exec(ctx, LoggerRepositoryAppend1,
		arg.EventType,
		arg.Level,
		arg.Message,
		arg.ActorType,
		arg.ActorID,
		arg.TraceID,
		arg.Result,
	)
	return err
}

const LoggerRepositoryGetList1 = `-- name: LoggerRepositoryGetList1 :many
SELECT id, at, event_type, level, message, actor_type, actor_id, trace_id, result FROM events ORDER BY at LIMIT $1 OFFSET $2
`

type LoggerRepositoryGetList1Params struct {
	Limit  int32
	Offset int32
}

func (q *Queries) LoggerRepositoryGetList1(ctx context.Context, arg LoggerRepositoryGetList1Params) ([]Event, error) {
	rows, err := q.db.Query(ctx, LoggerRepositoryGetList1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.EventType,
			&i.Level,
			&i.Message,
			&i.ActorType,
			&i.ActorID,
			&i.TraceID,
			&i.Result,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const LoggerRepositoryGetList2 = `-- name: LoggerRepositoryGetList2 :many
SELECT id, at, event_type, level, message, actor_type, actor_id, trace_id, result FROM events ORDER BY at OFFSET $1
`

func (q *Queries) LoggerRepositoryGetList2(ctx context.Context, offset int32) ([]Event, error) {
	rows, err := q.db.Query(ctx, LoggerRepositoryGetList2, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.EventType,
			&i.Level,
			&i.Message,
			&i.ActorType,
			&i.ActorID,
			&i.TraceID,
			&i.Result,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const LoginRepositoryAuthorization1 = `-- name: LoginRepositoryAuthorization1 :one
SELECT u.uid FROM users u WHERE u.username = $1
`

func (q *Queries) LoginRepositoryAuthorization1(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRow(ctx, LoginRepositoryAuthorization1, username)
	var uid int64
	err := row.Scan(&uid)
	return uid, err
}

const LoginRepositoryAuthorization2 = `-- name: LoginRepositoryAuthorization2 :one
SELECT u.uid FROM users u WHERE (u.email).address = $1
`

func (q *Queries) LoginRepositoryAuthorization2(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRow(ctx, LoginRepositoryAuthorization2, email)
	var uid int64
	err := row.Scan(&uid)
	return uid, err
}

const LoginRepositoryAuthorization3 = `-- name: LoginRepositoryAuthorization3 :one
SELECT u.password FROM users u WHERE u.uid = $1
`

func (q *Queries) LoginRepositoryAuthorization3(ctx context.Context, uid int64) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, LoginRepositoryAuthorization3, uid)
	var password pgtype.Text
	err := row.Scan(&password)
	return password, err
}

const LoginRepositoryGetOAuthUID1 = `-- name: LoginRepositoryGetOAuthUID1 :one
SELECT uid FROM oauth WHERE service = $1 AND linked_id = $2
`

type LoginRepositoryGetOAuthUID1Params struct {
	Service  OauthServiceEnum
	LinkedID string
}

func (q *Queries) LoginRepositoryGetOAuthUID1(ctx context.Context, arg LoginRepositoryGetOAuthUID1Params) (int64, error) {
	row := q.db.QueryRow(ctx, LoginRepositoryGetOAuthUID1, arg.Service, arg.LinkedID)
	var uid int64
	err := row.Scan(&uid)
	return uid, err
}

const LoginRepositoryGetUIDByEmail1 = `-- name: LoginRepositoryGetUIDByEmail1 :one
SELECT u.uid FROM users u WHERE lower((u.email).address) = lower($1)
`

func (q *Queries) LoginRepositoryGetUIDByEmail1(ctx context.Context, lower string) (int64, error) {
	row := q.db.QueryRow(ctx, LoginRepositoryGetUIDByEmail1, lower)
	var uid int64
	err := row.Scan(&uid)
	return uid, err
}

const LoginRepositoryLinkOAuth1 = `-- name: LoginRepositoryLinkOAuth1 :exec
INSERT INTO oauth (uid, service, linked_id)
		VALUES ($1, $2, $3)
		ON CONFLICT (service, uid)
		DO UPDATE SET linked_id = EXCLUDED.linked_id
`

type LoginRepositoryLinkOAuth1Params struct {
	Uid      int64
	Service  OauthServiceEnum
	LinkedID string
}

func (q *Queries) LoginRepositoryLinkOAuth1(ctx context.Context, arg LoginRepositoryLinkOAuth1Params) error {
	_, err := q.db.Exec(ctx, LoginRepositoryLinkOAuth1, arg.Uid, arg.Service, arg.LinkedID)
	return err
}

const LoginRepositoryLogout1 = `-- name: LoginRepositoryLogout1 :exec
UPDATE sessions SET revoked = true WHERE id = $1
`

func (q *Queries) LoginRepositoryLogout1(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, LoginRepositoryLogout1, id)
	return err
}

const LoginRepositoryRegister1 = `-- name: LoginRepositoryRegister1 :one
INSERT INTO users (username, email, password)
		VALUES (
		$1,
		ROW($2, false)::users_email_t,
		$3) RETURNING uid
`

type LoginRepositoryRegister1Params struct {
	Username string
	Column2  string
	Password pgtype.Text
}

func (q *Queries) LoginRepositoryRegister1(ctx context.Context, arg LoginRepositoryRegister1Params) (int64, error) {
	row := q.db.QueryRow(ctx, LoginRepositoryRegister1, arg.Username, arg.Column2, arg.Password)
	var uid int64
	err := row.Scan(&uid)
	return uid, err
}

const MaintenanceRepositoryCheckIsActive1 = `-- name: MaintenanceRepositoryCheckIsActive1 :one
SELECT EXISTS (SELECT 1 FROM maintenance m WHERE m.status = 'in progress')
`

func (q *Queries) MaintenanceRepositoryCheckIsActive1(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, MaintenanceRepositoryCheckIsActive1)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const MaintenanceRepositoryComplete1 = `-- name: MaintenanceRepositoryComplete1 :exec
UPDATE maintenance SET status = 'completed', actual_end_at = $1 WHERE status = 'in progress'
`

func (q *Queries) MaintenanceRepositoryComplete1(ctx context.Context, actualEndAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, MaintenanceRepositoryComplete1, actualEndAt)
	return err
}

const MaintenanceRepositoryEdit1 = `-- name: MaintenanceRepositoryEdit1 :exec
UPDATE maintenance SET description = $1 WHERE status = 'in progress'
`

func (q *Queries) MaintenanceRepositoryEdit1(ctx context.Context, description string) error {
	_, err := q.db.Exec(ctx, MaintenanceRepositoryEdit1, description)
	return err
}

const MaintenanceRepositoryEdit2 = `-- name: MaintenanceRepositoryEdit2 :exec
UPDATE maintenance SET scope = $1 WHERE status = 'in progress'
`

func (q *Queries) MaintenanceRepositoryEdit2(ctx context.Context, scope MaintenanceScope) error {
	_, err := q.db.Exec(ctx, MaintenanceRepositoryEdit2, scope)
	return err
}

const MaintenanceRepositoryGetData1 = `-- name: MaintenanceRepositoryGetData1 :one
SELECT m.id, m.description, m.status, m.scope, m.type, m.planned_start_at, m.planned_end_at, m.actual_start_at, m.actual_end_at, m.created_at, m.called_by FROM maintenance m WHERE m.status = 'in progress'
`

func (q *Queries) MaintenanceRepositoryGetData1(ctx context.Context) (Maintenance, error) {
	row := q.db.QueryRow(ctx, MaintenanceRepositoryGetData1)
	var i Maintenance
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Status,
		&i.Scope,
		&i.Type,
		&i.PlannedStartAt,
		&i.PlannedEndAt,
		&i.ActualStartAt,
		&i.ActualEndAt,
		&i.CreatedAt,
		&i.CalledBy,
	)
	return i, err
}

const MaintenanceRepositoryGetList1 = `-- name: MaintenanceRepositoryGetList1 :many
SELECT id, description, status, scope, type, planned_start_at, planned_end_at, actual_start_at, actual_end_at, created_at, called_by FROM maintenance
`

func (q *Queries) MaintenanceRepositoryGetList1(ctx context.Context) ([]Maintenance, error) {
	rows, err := q.db.Query(ctx, MaintenanceRepositoryGetList1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Maintenance
	for rows.Next() {
		var i Maintenance
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Status,
			&i.Scope,
			&i.Type,
			&i.PlannedStartAt,
			&i.PlannedEndAt,
			&i.ActualStartAt,
			&i.ActualEndAt,
			&i.CreatedAt,
			&i.CalledBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const MaintenanceRepositoryIsPlanned1 = `-- name: MaintenanceRepositoryIsPlanned1 :one
SELECT EXISTS (SELECT 1 FROM maintenance m WHERE m.status = 'scheduled')
`

func (q *Queries) MaintenanceRepositoryIsPlanned1(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, MaintenanceRepositoryIsPlanned1)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const MaintenanceRepositorySetActive1 = `-- name: MaintenanceRepositorySetActive1 :exec
UPDATE maintenance SET status = 'in progress', actual_start_at = $1 WHERE id = $2
`

type MaintenanceRepositorySetActive1Params struct {
	ActualStartAt pgtype.Timestamptz
	ID            pgtype.UUID
}

func (q *Queries) MaintenanceRepositorySetActive1(ctx context.Context, arg MaintenanceRepositorySetActive1Params) error {
	_, err := q.db.Exec(ctx, MaintenanceRepositorySetActive1, arg.ActualStartAt, arg.ID)
	return err
}

const MaintenanceRepositoryStart1 = `-- name: MaintenanceRepositoryStart1 :exec
INSERT INTO maintenance (description, scope, type, planned_start_at, planned_end_at, called_by) VALUES ($1, $2, $3, $4, $5, $6)
`

type MaintenanceRepositoryStart1Params struct {
	Description    string
	Scope          MaintenanceScope
	Type           MaintenanceType
	PlannedStartAt pgtype.Timestamptz
	PlannedEndAt   pgtype.Timestamptz
	CalledBy       int64
}

func (q *Queries) MaintenanceRepositoryStart1(ctx context.Context, arg MaintenanceRepositoryStart1Params) error {
	_, err := q.db.Exec(ctx, MaintenanceRepositoryStart1,
		arg.Description,
		arg.Scope,
		arg.Type,
		arg.PlannedStartAt,
		arg.PlannedEndAt,
		arg.CalledBy,
	)
	return err
}

const NotificationsRepositoryForUser1 = `-- name: NotificationsRepositoryForUser1 :many
SELECT n.id, n.body, n.createdAt, n.scope, n.expiresAt, nr.readAt
FROM notifications n
LEFT JOIN notification_receipts nr
  ON nr.notify_id = n.id AND nr.userID = $1
WHERE
  (n.expiresAt IS NULL OR n.expiresAt > now())
  AND (
    n.scope = 'broadcast'
    OR (n.scope = 'user' AND n.targetUserID = $1)
    OR (n.scope = 'segment' AND n.targetSegment = $2)
  )
  AND ($3::bool OR nr.readAt IS NULL)
ORDER BY n.createdAt DESC
`

type NotificationsRepositoryForUser1Params struct {
	Userid        int64
	Targetsegment pgtype.Text
	Column3       bool
}

type NotificationsRepositoryForUser1Row struct {
	ID        pgtype.UUID
	Body      string
	Createdat pgtype.Timestamptz
	Scope     NotificationScope
	Expiresat pgtype.Timestamptz
	Readat    pgtype.Timestamptz
}

func (q *Queries) NotificationsRepositoryForUser1(ctx context.Context, arg NotificationsRepositoryForUser1Params) ([]NotificationsRepositoryForUser1Row, error) {
	rows, err := q.db.Query(ctx, NotificationsRepositoryForUser1, arg.Userid, arg.Targetsegment, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationsRepositoryForUser1Row
	for rows.Next() {
		var i NotificationsRepositoryForUser1Row
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.Createdat,
			&i.Scope,
			&i.Expiresat,
			&i.Readat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const NotificationsRepositoryGetAll1 = `-- name: NotificationsRepositoryGetAll1 :many
SELECT id, body, createdAt, scope, targetUserID, targetSegment, expiresAt FROM notifications ORDER BY createdAt DESC
`

func (q *Queries) NotificationsRepositoryGetAll1(ctx context.Context) ([]Notification, error) {
	rows, err := q.db.Query(ctx, NotificationsRepositoryGetAll1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.Createdat,
			&i.Scope,
			&i.Targetuserid,
			&i.Targetsegment,
			&i.Expiresat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const NotificationsRepositoryInsertNotification1 = `-- name: NotificationsRepositoryInsertNotification1 :one
INSERT INTO notifications (body, scope, targetUserID, targetSegment, expiresAt) VALUES ($1, $2, $3, $4, $5) RETURNING id
`

type NotificationsRepositoryInsertNotification1Params struct {
	Body          string
	Scope         NotificationScope
	Targetuserid  pgtype.Int8
	Targetsegment pgtype.Text
	Expiresat     pgtype.Timestamptz
}

func (q *Queries) NotificationsRepositoryInsertNotification1(ctx context.Context, arg NotificationsRepositoryInsertNotification1Params) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, NotificationsRepositoryInsertNotification1,
		arg.Body,
		arg.Scope,
		arg.Targetuserid,
		arg.Targetsegment,
		arg.Expiresat,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const NotificationsRepositoryMark1 = `-- name: NotificationsRepositoryMark1 :exec
INSERT INTO notification_receipts (notify_id, userID, readAt)
		 VALUES ($1, $2, now())
		 ON CONFLICT (notify_id, userID)
		 DO UPDATE SET readAt = EXCLUDED.readAt
`

type NotificationsRepositoryMark1Params struct {
	NotifyID pgtype.UUID
	Userid   int64
}

func (q *Queries) NotificationsRepositoryMark1(ctx context.Context, arg NotificationsRepositoryMark1Params) error {
	_, err := q.db.Exec(ctx, NotificationsRepositoryMark1, arg.NotifyID, arg.Userid)
	return err
}

const ProjectsRepositoryCreateMessage1 = `-- name: ProjectsRepositoryCreateMessage1 :one
SELECT EXISTS(SELECT 1 FROM projects WHERE id = $1)
`

func (q *Queries) ProjectsRepositoryCreateMessage1(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, ProjectsRepositoryCreateMessage1, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const ProjectsRepositoryCreateMessage2 = `-- name: ProjectsRepositoryCreateMessage2 :one
SELECT EXISTS(SELECT 1 FROM project_messages WHERE project_id = $1 AND id = $2)
`

type ProjectsRepositoryCreateMessage2Params struct {
	ProjectID pgtype.UUID
	ID        int64
}

func (q *Queries) ProjectsRepositoryCreateMessage2(ctx context.Context, arg ProjectsRepositoryCreateMessage2Params) (bool, error) {
	row := q.db.QueryRow(ctx, ProjectsRepositoryCreateMessage2, arg.ProjectID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const ProjectsRepositoryCreateMessage3 = `-- name: ProjectsRepositoryCreateMessage3 :exec
INSERT INTO project_messages (project_id, author_uid, content, reply_to_id) VALUES ($1, $2, $3, $4)
`

type ProjectsRepositoryCreateMessage3Params struct {
	ProjectID pgtype.UUID
	AuthorUid int64
	Content   string
	ReplyToID pgtype.Int8
}

func (q *Queries) ProjectsRepositoryCreateMessage3(ctx context.Context, arg ProjectsRepositoryCreateMessage3Params) error {
	_, err := q.db.Exec(ctx, ProjectsRepositoryCreateMessage3,
		arg.ProjectID,
		arg.AuthorUid,
		arg.Content,
		arg.ReplyToID,
	)
	return err
}

const ProjectsRepositoryCreateProject1 = `-- name: ProjectsRepositoryCreateProject1 :one
INSERT INTO projects (author_uid, info) VALUES ($1, ROW($2, $3, $4::project_categories, ROW($5, $6, $7, $8)::project_location_t)::project_info_t) RETURNING id
`

type ProjectsRepositoryCreateProject1Params struct {
	AuthorUid int64
	Column2   string
	Column3   string
	Column4   ProjectCategories
	Column5   string
	Column6   string
	Column7   string
	Column8   string
}

func (q *Queries) ProjectsRepositoryCreateProject1(ctx context.Context, arg ProjectsRepositoryCreateProject1Params) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, ProjectsRepositoryCreateProject1,
		arg.AuthorUid,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const ProjectsRepositoryCreateProject2 = `-- name: ProjectsRepositoryCreateProject2 :exec
INSERT INTO project_photos (project_id, object_key, content_type, size_bytes, created_at)
		VALUES ($1, $2, $3, $4, now())
		ON CONFLICT (object_key) DO NOTHING
`

type ProjectsRepositoryCreateProject2Params struct {
	ProjectID   pgtype.UUID
	ObjectKey   string
	ContentType pgtype.Text
	SizeBytes   pgtype.Int8
}

func (q *Queries) ProjectsRepositoryCreateProject2(ctx context.Context, arg ProjectsRepositoryCreateProject2Params) error {
	_, err := q.db.Exec(ctx, ProjectsRepositoryCreateProject2,
		arg.ProjectID,
		arg.ObjectKey,
		arg.ContentType,
		arg.SizeBytes,
	)
	return err
}

const ProjectsRepositoryCreateProject3 = `-- name: ProjectsRepositoryCreateProject3 :exec
INSERT INTO submissions (project_id) VALUES ($1)
`

func (q *Queries) ProjectsRepositoryCreateProject3(ctx context.Context, projectID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, ProjectsRepositoryCreateProject3, projectID)
	return err
}

const ProjectsRepositoryGetProjectsByUID1 = `-- name: ProjectsRepositoryGetProjectsByUID1 :many
SELECT p.id FROM projects p WHERE p.author_uid = $1
`

func (q *Queries) ProjectsRepositoryGetProjectsByUID1(ctx context.Context, authorUid int64) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, ProjectsRepositoryGetProjectsByUID1, authorUid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ProjectsRepositoryMessages1 = `-- name: ProjectsRepositoryMessages1 :one
SELECT EXISTS(SELECT 1 FROM projects WHERE id = $1)
`

func (q *Queries) ProjectsRepositoryMessages1(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, ProjectsRepositoryMessages1, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const ProjectsRepositoryMessages2 = `-- name: ProjectsRepositoryMessages2 :many
SELECT
			id,
			project_id,
			author_uid,
			content,
			reply_to_id,
			at
		FROM project_messages
		WHERE project_id = $1
		ORDER BY at ASC, id ASC
`

func (q *Queries) ProjectsRepositoryMessages2(ctx context.Context, projectID pgtype.UUID) ([]ProjectMessage, error) {
	rows, err := q.db.Query(ctx, ProjectsRepositoryMessages2, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectMessage
	for rows.Next() {
		var i ProjectMessage
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AuthorUid,
			&i.Content,
			&i.ReplyToID,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ProjectsRepositoryToggleLike1 = `-- name: ProjectsRepositoryToggleLike1 :one
select toggle_project_like($1::uuid, $2::bigint)
`

type ProjectsRepositoryToggleLike1Params struct {
	Column1 pgtype.UUID
	Column2 int64
}

func (q *Queries) ProjectsRepositoryToggleLike1(ctx context.Context, arg ProjectsRepositoryToggleLike1Params) (bool, error) {
	row := q.db.QueryRow(ctx, ProjectsRepositoryToggleLike1, arg.Column1, arg.Column2)
	var toggle_project_like bool
	err := row.Scan(&toggle_project_like)
	return toggle_project_like, err
}

const RanksRepositoryCanEdit1 = `-- name: RanksRepositoryCanEdit1 :one
SELECT COALESCE(r1.weight, 0) > COALESCE(r2.weight, 0) AS can_edit FROM (SELECT ranks.weight FROM ranks WHERE ranks.name = $1) r1 CROSS JOIN (SELECT ranks.weight FROM ranks WHERE ranks.name = $2) r2
`

type RanksRepositoryCanEdit1Params struct {
	Name   string
	Name_2 string
}

func (q *Queries) RanksRepositoryCanEdit1(ctx context.Context, arg RanksRepositoryCanEdit1Params) (bool, error) {
	row := q.db.QueryRow(ctx, RanksRepositoryCanEdit1, arg.Name, arg.Name_2)
	var can_edit bool
	err := row.Scan(&can_edit)
	return can_edit, err
}

const RanksRepositoryChangePerms1 = `-- name: RanksRepositoryChangePerms1 :exec
UPDATE ranks r
		 SET permissions = perm_set(r.permissions, $1, $2)
		 WHERE r.name = $3
`

type RanksRepositoryChangePerms1Params struct {
	Perm  string
	State bool
	Name  string
}

func (q *Queries) RanksRepositoryChangePerms1(ctx context.Context, arg RanksRepositoryChangePerms1Params) error {
	_, err := q.db.Exec(ctx, RanksRepositoryChangePerms1, arg.Perm, arg.State, arg.Name)
	return err
}

const RanksRepositoryCreate1 = `-- name: RanksRepositoryCreate1 :exec
INSERT INTO ranks (name, color, description, permissions)
			VALUES ($1, $2, $3, jsonb_populate_record(null::permissions_t, $4::jsonb))
`

type RanksRepositoryCreate1Params struct {
	Name        string
	Color       int32
	Description string
	Column4     []byte
}

func (q *Queries) RanksRepositoryCreate1(ctx context.Context, arg RanksRepositoryCreate1Params) error {
	_, err := q.db.Exec(ctx, RanksRepositoryCreate1,
		arg.Name,
		arg.Color,
		arg.Description,
		arg.Column4,
	)
	return err
}

const RanksRepositoryCreate2 = `-- name: RanksRepositoryCreate2 :exec
INSERT INTO ranks (name, color, description) VALUES ($1, $2, $3)
`

type RanksRepositoryCreate2Params struct {
	Name        string
	Color       int32
	Description string
}

func (q *Queries) RanksRepositoryCreate2(ctx context.Context, arg RanksRepositoryCreate2Params) error {
	_, err := q.db.Exec(ctx, RanksRepositoryCreate2, arg.Name, arg.Color, arg.Description)
	return err
}

const RanksRepositoryCreateActivations1 = `-- name: RanksRepositoryCreateActivations1 :exec
INSERT INTO rank_activations (code, rank) VALUES ($1, $2)
`

type RanksRepositoryCreateActivations1Params struct {
	Code pgtype.UUID
	Rank string
}

func (q *Queries) RanksRepositoryCreateActivations1(ctx context.Context, arg RanksRepositoryCreateActivations1Params) error {
	_, err := q.db.Exec(ctx, RanksRepositoryCreateActivations1, arg.Code, arg.Rank)
	return err
}

const RanksRepositoryDelete1 = `-- name: RanksRepositoryDelete1 :exec
DELETE FROM ranks WHERE name = $1
`

func (q *Queries) RanksRepositoryDelete1(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, RanksRepositoryDelete1, name)
	return err
}

const RanksRepositoryGet1 = `-- name: RanksRepositoryGet1 :one
SELECT color, description, added_at FROM ranks WHERE name = $1
`

type RanksRepositoryGet1Row struct {
	Color       int32
	Description string
	AddedAt     pgtype.Timestamptz
}

func (q *Queries) RanksRepositoryGet1(ctx context.Context, name string) (RanksRepositoryGet1Row, error) {
	row := q.db.QueryRow(ctx, RanksRepositoryGet1, name)
	var i RanksRepositoryGet1Row
	err := row.Scan(&i.Color, &i.Description, &i.AddedAt)
	return i, err
}

const RanksRepositoryIsExists1 = `-- name: RanksRepositoryIsExists1 :one
SELECT EXISTS (SELECT 1 FROM ranks WHERE name = $1)
`

func (q *Queries) RanksRepositoryIsExists1(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, RanksRepositoryIsExists1, name)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const RanksRepositoryList1 = `-- name: RanksRepositoryList1 :many
SELECT r.name, r.color, r.description, r.weight, r.permissions, r.added_at FROM ranks r ORDER BY r.added_at DESC
`

func (q *Queries) RanksRepositoryList1(ctx context.Context) ([]Rank, error) {
	rows, err := q.db.Query(ctx, RanksRepositoryList1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rank
	for rows.Next() {
		var i Rank
		if err := rows.Scan(
			&i.Name,
			&i.Color,
			&i.Description,
			&i.Weight,
			&i.Permissions,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RanksRepositoryPerms1 = `-- name: RanksRepositoryPerms1 :one
SELECT to_jsonb(r.permissions) FROM ranks r WHERE r.name = $1
`

func (q *Queries) RanksRepositoryPerms1(ctx context.Context, name string) ([]byte, error) {
	row := q.db.QueryRow(ctx, RanksRepositoryPerms1, name)
	var to_jsonb []byte
	err := row.Scan(&to_jsonb)
	return to_jsonb, err
}

const RanksRepositoryUsersWithRank1 = `-- name: RanksRepositoryUsersWithRank1 :many
SELECT u.uid FROM users u WHERE (u.rank).name = $1
`

func (q *Queries) RanksRepositoryUsersWithRank1(ctx context.Context, rank string) ([]int64, error) {
	rows, err := q.db.Query(ctx, RanksRepositoryUsersWithRank1, rank)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var uid int64
		if err := rows.Scan(&uid); err != nil {
			return nil, err
		}
		items = append(items, uid)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SessionsRepositoryAddSession1 = `-- name: SessionsRepositoryAddSession1 :exec
INSERT INTO sessions (id, uid, expires, user_agent_hash) VALUES ($1,$2, $3, $4)
`

type SessionsRepositoryAddSession1Params struct {
	ID            pgtype.UUID
	Uid           int64
	Expires       pgtype.Timestamptz
	UserAgentHash string
}

func (q *Queries) SessionsRepositoryAddSession1(ctx context.Context, arg SessionsRepositoryAddSession1Params) error {
	_, err := q.db.Exec(ctx, SessionsRepositoryAddSession1,
		arg.ID,
		arg.Uid,
		arg.Expires,
		arg.UserAgentHash,
	)
	return err
}

const SessionsRepositoryGetSession1 = `-- name: SessionsRepositoryGetSession1 :one
SELECT id, uid, created_at, last_seen_at, expires, revoked, mfa_complete, user_agent_hash FROM sessions s WHERE s.id = $1
`

func (q *Queries) SessionsRepositoryGetSession1(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, SessionsRepositoryGetSession1, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.Expires,
		&i.Revoked,
		&i.MfaComplete,
		&i.UserAgentHash,
	)
	return i, err
}

const SessionsRepositoryGetSessions1 = `-- name: SessionsRepositoryGetSessions1 :many
SELECT id FROM sessions s WHERE s.uid = $1 AND s.revoked = false AND s.expires > NOW() ORDER BY s.last_seen_at DESC NULLS LAST, s.created_at DESC
`

func (q *Queries) SessionsRepositoryGetSessions1(ctx context.Context, uid int64) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, SessionsRepositoryGetSessions1, uid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SessionsRepositoryGetUID1 = `-- name: SessionsRepositoryGetUID1 :one
SELECT uid FROM sessions s WHERE s.id = $1
`

func (q *Queries) SessionsRepositoryGetUID1(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, SessionsRepositoryGetUID1, id)
	var uid int64
	err := row.Scan(&uid)
	return uid, err
}

const SessionsRepositoryResetMFAs1 = `-- name: SessionsRepositoryResetMFAs1 :exec
UPDATE sessions SET mfa_complete = false WHERE uid = $1
`

func (q *Queries) SessionsRepositoryResetMFAs1(ctx context.Context, uid int64) error {
	_, err := q.db.Exec(ctx, SessionsRepositoryResetMFAs1, uid)
	return err
}

const SessionsRepositorySetMFACompleted1 = `-- name: SessionsRepositorySetMFACompleted1 :exec
UPDATE sessions SET mfa_complete = true WHERE id = $1
`

func (q *Queries) SessionsRepositorySetMFACompleted1(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, SessionsRepositorySetMFACompleted1, id)
	return err
}

const SessionsRepositorySetRevoked1 = `-- name: SessionsRepositorySetRevoked1 :exec
UPDATE sessions SET revoked = true WHERE id = $1
`

func (q *Queries) SessionsRepositorySetRevoked1(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, SessionsRepositorySetRevoked1, id)
	return err
}

const SessionsRepositoryUpdateLastSeen1 = `-- name: SessionsRepositoryUpdateLastSeen1 :exec
UPDATE sessions SET last_seen_at = $1 WHERE id = $2
`

type SessionsRepositoryUpdateLastSeen1Params struct {
	LastSeenAt pgtype.Timestamptz
	ID         pgtype.UUID
}

func (q *Queries) SessionsRepositoryUpdateLastSeen1(ctx context.Context, arg SessionsRepositoryUpdateLastSeen1Params) error {
	_, err := q.db.Exec(ctx, SessionsRepositoryUpdateLastSeen1, arg.LastSeenAt, arg.ID)
	return err
}

const StatisticsRepositoryGetOfflineUsers1 = `-- name: StatisticsRepositoryGetOfflineUsers1 :one
SELECT
		  (SELECT COUNT(*) FROM users)::bigint -
		  (SELECT COUNT(DISTINCT e.actor_id)  FILTER ( WHERE e.actor_id != 0 ) FROM events e WHERE e.at >= $1)::bigint
`

func (q *Queries) StatisticsRepositoryGetOfflineUsers1(ctx context.Context, at pgtype.Timestamptz) (int32, error) {
	row := q.db.QueryRow(ctx, StatisticsRepositoryGetOfflineUsers1, at)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const StatisticsRepositoryGetOnlineUsers1 = `-- name: StatisticsRepositoryGetOnlineUsers1 :one
SELECT COUNT(DISTINCT e.actor_id) FILTER ( WHERE e.actor_id != 0 )
		 FROM events e
		 WHERE e.at >= $1
`

func (q *Queries) StatisticsRepositoryGetOnlineUsers1(ctx context.Context, at pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, StatisticsRepositoryGetOnlineUsers1, at)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const StatisticsRepositoryIdeasRecap1 = `-- name: StatisticsRepositoryIdeasRecap1 :one
SELECT
			COUNT(*) FILTER (WHERE state = 'waiting')  AS waiting,
			COUNT(*) FILTER (WHERE state = 'approved') AS approved,
			COUNT(*) FILTER (WHERE state = 'declined') AS declined
		FROM submissions
`

type StatisticsRepositoryIdeasRecap1Row struct {
	Waiting  int64
	Approved int64
	Declined int64
}

func (q *Queries) StatisticsRepositoryIdeasRecap1(ctx context.Context) (StatisticsRepositoryIdeasRecap1Row, error) {
	row := q.db.QueryRow(ctx, StatisticsRepositoryIdeasRecap1)
	var i StatisticsRepositoryIdeasRecap1Row
	err := row.Scan(&i.Waiting, &i.Approved, &i.Declined)
	return i, err
}

const StatisticsRepositoryNewIdeasCount1 = `-- name: StatisticsRepositoryNewIdeasCount1 :one
SELECT COUNT(*) FROM projects WHERE created_at >= $1
`

func (q *Queries) StatisticsRepositoryNewIdeasCount1(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, StatisticsRepositoryNewIdeasCount1, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const StatisticsRepositoryQualityRecap1 = `-- name: StatisticsRepositoryQualityRecap1 :one
SELECT
		    COUNT (*) FILTER (WHERE rate = 'good') AS good,
		    COUNT (*) FILTER (WHERE rate = 'bad') AS bad
		FROM pictures
`

type StatisticsRepositoryQualityRecap1Row struct {
	Good int64
	Bad  int64
}

func (q *Queries) StatisticsRepositoryQualityRecap1(ctx context.Context) (StatisticsRepositoryQualityRecap1Row, error) {
	row := q.db.QueryRow(ctx, StatisticsRepositoryQualityRecap1)
	var i StatisticsRepositoryQualityRecap1Row
	err := row.Scan(&i.Good, &i.Bad)
	return i, err
}

const StatisticsRepositorySaveStatisticsRecap1 = `-- name: StatisticsRepositorySaveStatisticsRecap1 :exec
INSERT INTO statistics_recap (at, us_activity, new_ideas, vote_count) VALUES ($1, ROW($2, $3)::users_activity_t, $4, $5)
`

type StatisticsRepositorySaveStatisticsRecap1Params struct {
	At        pgtype.Timestamptz
	Column2   string
	Column3   string
	NewIdeas  int64
	VoteCount int64
}

func (q *Queries) StatisticsRepositorySaveStatisticsRecap1(ctx context.Context, arg StatisticsRepositorySaveStatisticsRecap1Params) error {
	_, err := q.db.Exec(ctx, StatisticsRepositorySaveStatisticsRecap1,
		arg.At,
		arg.Column2,
		arg.Column3,
		arg.NewIdeas,
		arg.VoteCount,
	)
	return err
}

const StatisticsRepositoryStatisticsRecap1 = `-- name: StatisticsRepositoryStatisticsRecap1 :many
SELECT
			s.id,
			s.at,
			(s.us_activity).online,
			(s.us_activity).offline,
			s.new_ideas,
			s.vote_count
		FROM statistics_recap s
		WHERE s.at >= $1
`

type StatisticsRepositoryStatisticsRecap1Row struct {
	ID        pgtype.UUID
	At        pgtype.Timestamptz
	Column3   interface{}
	Column4   interface{}
	NewIdeas  int64
	VoteCount int64
}

func (q *Queries) StatisticsRepositoryStatisticsRecap1(ctx context.Context, at pgtype.Timestamptz) ([]StatisticsRepositoryStatisticsRecap1Row, error) {
	rows, err := q.db.Query(ctx, StatisticsRepositoryStatisticsRecap1, at)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatisticsRepositoryStatisticsRecap1Row
	for rows.Next() {
		var i StatisticsRepositoryStatisticsRecap1Row
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.Column3,
			&i.Column4,
			&i.NewIdeas,
			&i.VoteCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const StatisticsRepositoryVoteCount1 = `-- name: StatisticsRepositoryVoteCount1 :one
SELECT COUNT(*) FROM project_likes WHERE created_at >= $1
`

func (q *Queries) StatisticsRepositoryVoteCount1(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, StatisticsRepositoryVoteCount1, createdAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const SubmissionsRepositoryAlreadySetted1 = `-- name: SubmissionsRepositoryAlreadySetted1 :one
SELECT EXISTS (SELECT 1 FROM submissions WHERE id = $1 AND state <> 'waiting')
`

func (q *Queries) SubmissionsRepositoryAlreadySetted1(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, SubmissionsRepositoryAlreadySetted1, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const SubmissionsRepositoryApprove1 = `-- name: SubmissionsRepositoryApprove1 :exec
WITH upd AS (
			UPDATE submissions
			SET state = 'approved'
			WHERE submissions.id = $1
			RETURNING project_id
		)
		UPDATE projects
		SET status = 'published'
		WHERE projects.id = (SELECT upd.project_id FROM upd)
`

func (q *Queries) SubmissionsRepositoryApprove1(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, SubmissionsRepositoryApprove1, id)
	return err
}

const SubmissionsRepositoryDecline1 = `-- name: SubmissionsRepositoryDecline1 :exec
UPDATE submissions SET state = 'declined', reason = $1 WHERE id = $2
`

type SubmissionsRepositoryDecline1Params struct {
	Reason pgtype.Text
	ID     int64
}

func (q *Queries) SubmissionsRepositoryDecline1(ctx context.Context, arg SubmissionsRepositoryDecline1Params) error {
	_, err := q.db.Exec(ctx, SubmissionsRepositoryDecline1, arg.Reason, arg.ID)
	return err
}

const SubmissionsRepositoryGetByID1 = `-- name: SubmissionsRepositoryGetByID1 :one
SELECT s.project_id, s.state, s.reason FROM submissions s WHERE s.id = $1
`

type SubmissionsRepositoryGetByID1Row struct {
	ProjectID pgtype.UUID
	State     SubmissionsState
	Reason    pgtype.Text
}

func (q *Queries) SubmissionsRepositoryGetByID1(ctx context.Context, id int64) (SubmissionsRepositoryGetByID1Row, error) {
	row := q.db.QueryRow(ctx, SubmissionsRepositoryGetByID1, id)
	var i SubmissionsRepositoryGetByID1Row
	err := row.Scan(&i.ProjectID, &i.State, &i.Reason)
	return i, err
}

const SubmissionsRepositoryGetList1 = `-- name: SubmissionsRepositoryGetList1 :many
SELECT s.id, s.project_id, s.state, s.reason FROM submissions s
`

func (q *Queries) SubmissionsRepositoryGetList1(ctx context.Context) ([]Submission, error) {
	rows, err := q.db.Query(ctx, SubmissionsRepositoryGetList1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.State,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const TicketsRepositoryAccept1 = `-- name: TicketsRepositoryAccept1 :exec
UPDATE tickets SET acceptor = $1, accepted = $2, status = $3 WHERE id = $4 AND status <> $3
`

type TicketsRepositoryAccept1Params struct {
	Acceptor pgtype.Int8
	Accepted pgtype.Timestamptz
	Status   TicketStatus
	ID       pgtype.UUID
}

func (q *Queries) TicketsRepositoryAccept1(ctx context.Context, arg TicketsRepositoryAccept1Params) error {
	_, err := q.db.Exec(ctx, TicketsRepositoryAccept1,
		arg.Acceptor,
		arg.Accepted,
		arg.Status,
		arg.ID,
	)
	return err
}

const TicketsRepositoryAccept2 = `-- name: TicketsRepositoryAccept2 :one
SELECT acceptor FROM tickets WHERE id = $1
`

func (q *Queries) TicketsRepositoryAccept2(ctx context.Context, id pgtype.UUID) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, TicketsRepositoryAccept2, id)
	var acceptor pgtype.Int8
	err := row.Scan(&acceptor)
	return acceptor, err
}

const TicketsRepositoryAccepted1 = `-- name: TicketsRepositoryAccepted1 :one
SELECT status = 'в обработке' FROM tickets WHERE id = $1
`

func (q *Queries) TicketsRepositoryAccepted1(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, TicketsRepositoryAccepted1, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const TicketsRepositoryClose1 = `-- name: TicketsRepositoryClose1 :exec
UPDATE tickets SET closed = NOW(), closed_by = $1, close_reason = $2, status = $3 WHERE id = $4
`

type TicketsRepositoryClose1Params struct {
	ClosedBy    NullTicketCloseBy
	CloseReason pgtype.Text
	Status      TicketStatus
	ID          pgtype.UUID
}

func (q *Queries) TicketsRepositoryClose1(ctx context.Context, arg TicketsRepositoryClose1Params) error {
	_, err := q.db.Exec(ctx, TicketsRepositoryClose1,
		arg.ClosedBy,
		arg.CloseReason,
		arg.Status,
		arg.ID,
	)
	return err
}

const TicketsRepositoryCreate1 = `-- name: TicketsRepositoryCreate1 :one
INSERT INTO tickets (name, email, topic, brief, authorized_uid, authorized) VALUES ($1, $2, $3, $4, $5, true) RETURNING id
`

type TicketsRepositoryCreate1Params struct {
	Name          pgtype.Text
	Email         pgtype.Text
	Topic         TicketTopic
	Brief         string
	AuthorizedUid pgtype.Int8
}

func (q *Queries) TicketsRepositoryCreate1(ctx context.Context, arg TicketsRepositoryCreate1Params) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, TicketsRepositoryCreate1,
		arg.Name,
		arg.Email,
		arg.Topic,
		arg.Brief,
		arg.AuthorizedUid,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const TicketsRepositoryCreate2 = `-- name: TicketsRepositoryCreate2 :one
INSERT INTO tickets (name, email, topic, brief, requestor_token) VALUES ($1, $2, $3, $4, $5) RETURNING id
`

type TicketsRepositoryCreate2Params struct {
	Name           pgtype.Text
	Email          pgtype.Text
	Topic          TicketTopic
	Brief          string
	RequestorToken pgtype.Text
}

func (q *Queries) TicketsRepositoryCreate2(ctx context.Context, arg TicketsRepositoryCreate2Params) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, TicketsRepositoryCreate2,
		arg.Name,
		arg.Email,
		arg.Topic,
		arg.Brief,
		arg.RequestorToken,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const TicketsRepositoryCreate3 = `-- name: TicketsRepositoryCreate3 :exec
INSERT INTO ticket_messages (ticket, author_type, content) VALUES ($1, $2, $3)
`

type TicketsRepositoryCreate3Params struct {
	Ticket     pgtype.UUID
	AuthorType TicketMessageAuthor
	Content    string
}

func (q *Queries) TicketsRepositoryCreate3(ctx context.Context, arg TicketsRepositoryCreate3Params) error {
	_, err := q.db.Exec(ctx, TicketsRepositoryCreate3, arg.Ticket, arg.AuthorType, arg.Content)
	return err
}

const TicketsRepositoryCreateMessage1 = `-- name: TicketsRepositoryCreateMessage1 :exec
INSERT INTO ticket_messages (ticket, author_uid, author_name, author_email, author_type, content) VALUES ($1, $2, $3, $4, $5, $6)
`

type TicketsRepositoryCreateMessage1Params struct {
	Ticket      pgtype.UUID
	AuthorUid   pgtype.Int8
	AuthorName  pgtype.Text
	AuthorEmail pgtype.Text
	AuthorType  TicketMessageAuthor
	Content     string
}

func (q *Queries) TicketsRepositoryCreateMessage1(ctx context.Context, arg TicketsRepositoryCreateMessage1Params) error {
	_, err := q.db.Exec(ctx, TicketsRepositoryCreateMessage1,
		arg.Ticket,
		arg.AuthorUid,
		arg.AuthorName,
		arg.AuthorEmail,
		arg.AuthorType,
		arg.Content,
	)
	return err
}

const TicketsRepositoryCreateMessage2 = `-- name: TicketsRepositoryCreateMessage2 :exec
INSERT INTO ticket_messages (ticket, author_name, author_email, author_type, content) VALUES ($1, $2, $3, $4, $5)
`

type TicketsRepositoryCreateMessage2Params struct {
	Ticket      pgtype.UUID
	AuthorName  pgtype.Text
	AuthorEmail pgtype.Text
	AuthorType  TicketMessageAuthor
	Content     string
}

func (q *Queries) TicketsRepositoryCreateMessage2(ctx context.Context, arg TicketsRepositoryCreateMessage2Params) error {
	_, err := q.db.Exec(ctx, TicketsRepositoryCreateMessage2,
		arg.Ticket,
		arg.AuthorName,
		arg.AuthorEmail,
		arg.AuthorType,
		arg.Content,
	)
	return err
}

const TicketsRepositoryDeleteMessage1 = `-- name: TicketsRepositoryDeleteMessage1 :exec
UPDATE ticket_messages SET deleted_at = NOW(), deleted_by = $1 WHERE ticket = $2 AND id = $3 AND deleted_at IS NULL
`

type TicketsRepositoryDeleteMessage1Params struct {
	DeletedBy pgtype.Int8
	Ticket    pgtype.UUID
	ID        int64
}

func (q *Queries) TicketsRepositoryDeleteMessage1(ctx context.Context, arg TicketsRepositoryDeleteMessage1Params) error {
	_, err := q.db.Exec(ctx, TicketsRepositoryDeleteMessage1, arg.DeletedBy, arg.Ticket, arg.ID)
	return err
}

const TicketsRepositoryEditMessage1 = `-- name: TicketsRepositoryEditMessage1 :exec
UPDATE ticket_messages SET content = $1, edited_at = NOW() WHERE ticket = $2 AND id = $3 AND deleted_at IS NULL
`

type TicketsRepositoryEditMessage1Params struct {
	Content string
	Ticket  pgtype.UUID
	ID      int64
}

func (q *Queries) TicketsRepositoryEditMessage1(ctx context.Context, arg TicketsRepositoryEditMessage1Params) error {
	_, err := q.db.Exec(ctx, TicketsRepositoryEditMessage1, arg.Content, arg.Ticket, arg.ID)
	return err
}

const TicketsRepositoryGetLatestMessage1 = `-- name: TicketsRepositoryGetLatestMessage1 :one
SELECT
			m.id,
			m.ticket,
			m.author_type,
			m.author_uid,
			m.author_name,
			m.author_email,
			m.content,
			m.at,
			m.edited_at,
			m.deleted_at,
			m.deleted_by
		FROM ticket_messages m
		WHERE m.ticket = $1
		ORDER BY m.at DESC, m.id DESC
		LIMIT 1
`

func (q *Queries) TicketsRepositoryGetLatestMessage1(ctx context.Context, ticket pgtype.UUID) (TicketMessage, error) {
	row := q.db.QueryRow(ctx, TicketsRepositoryGetLatestMessage1, ticket)
	var i TicketMessage
	err := row.Scan(
		&i.ID,
		&i.Ticket,
		&i.AuthorType,
		&i.AuthorUid,
		&i.AuthorName,
		&i.AuthorEmail,
		&i.Content,
		&i.At,
		&i.EditedAt,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const TicketsRepositoryInfo1 = `-- name: TicketsRepositoryInfo1 :one
SELECT t.id, t.name, t.email, t.authorized, t.authorized_uid, t.requestor_token, t.count, t.acceptor, t.status, t.topic, t.brief, t.created, t.accepted, t.closed, t.closed_by, t.close_reason FROM tickets t WHERE t.id = $1
`

func (q *Queries) TicketsRepositoryInfo1(ctx context.Context, id pgtype.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, TicketsRepositoryInfo1, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Authorized,
		&i.AuthorizedUid,
		&i.RequestorToken,
		&i.Count,
		&i.Acceptor,
		&i.Status,
		&i.Topic,
		&i.Brief,
		&i.Created,
		&i.Accepted,
		&i.Closed,
		&i.ClosedBy,
		&i.CloseReason,
	)
	return i, err
}

const TicketsRepositoryIsClosed1 = `-- name: TicketsRepositoryIsClosed1 :one
SELECT status = 'закрыт' FROM tickets WHERE id = $1
`

func (q *Queries) TicketsRepositoryIsClosed1(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, TicketsRepositoryIsClosed1, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const TicketsRepositoryIsReqValid1 = `-- name: TicketsRepositoryIsReqValid1 :one
SELECT EXISTS (SELECT 1 FROM tickets WHERE requestor_token = $1 AND id = $2)
`

type TicketsRepositoryIsReqValid1Params struct {
	RequestorToken pgtype.Text
	ID             pgtype.UUID
}

func (q *Queries) TicketsRepositoryIsReqValid1(ctx context.Context, arg TicketsRepositoryIsReqValid1Params) (bool, error) {
	row := q.db.QueryRow(ctx, TicketsRepositoryIsReqValid1, arg.RequestorToken, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const TicketsRepositoryIsReqValid2 = `-- name: TicketsRepositoryIsReqValid2 :one
SELECT EXISTS (SELECT 1 FROM tickets WHERE authorized_uid = $1 AND id = $2)
`

type TicketsRepositoryIsReqValid2Params struct {
	AuthorizedUid pgtype.Int8
	ID            pgtype.UUID
}

func (q *Queries) TicketsRepositoryIsReqValid2(ctx context.Context, arg TicketsRepositoryIsReqValid2Params) (bool, error) {
	row := q.db.QueryRow(ctx, TicketsRepositoryIsReqValid2, arg.AuthorizedUid, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const TicketsRepositoryLatestAt1 = `-- name: TicketsRepositoryLatestAt1 :one
SELECT at FROM ticket_messages WHERE ticket = $1 ORDER BY at DESC LIMIT 1
`

func (q *Queries) TicketsRepositoryLatestAt1(ctx context.Context, ticket pgtype.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, TicketsRepositoryLatestAt1, ticket)
	var at pgtype.Timestamptz
	err := row.Scan(&at)
	return at, err
}

const TicketsRepositoryList1 = `-- name: TicketsRepositoryList1 :many
SELECT t.id, t.name, t.email, t.authorized, t.authorized_uid, t.requestor_token, t.count, t.acceptor, t.status, t.topic, t.brief, t.created, t.accepted, t.closed, t.closed_by, t.close_reason FROM tickets t ORDER BY t.created DESC
`

func (q *Queries) TicketsRepositoryList1(ctx context.Context) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, TicketsRepositoryList1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Authorized,
			&i.AuthorizedUid,
			&i.RequestorToken,
			&i.Count,
			&i.Acceptor,
			&i.Status,
			&i.Topic,
			&i.Brief,
			&i.Created,
			&i.Accepted,
			&i.Closed,
			&i.ClosedBy,
			&i.CloseReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const TicketsRepositoryList2 = `-- name: TicketsRepositoryList2 :many
SELECT t.id, t.name, t.email, t.authorized, t.authorized_uid, t.requestor_token, t.count, t.acceptor, t.status, t.topic, t.brief, t.created, t.accepted, t.closed, t.closed_by, t.close_reason FROM tickets t WHERE t.authorized = $1 AND t.authorized_uid = $2 ORDER BY t.created DESC
`

type TicketsRepositoryList2Params struct {
	Authorized    bool
	AuthorizedUid pgtype.Int8
}

func (q *Queries) TicketsRepositoryList2(ctx context.Context, arg TicketsRepositoryList2Params) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, TicketsRepositoryList2, arg.Authorized, arg.AuthorizedUid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Authorized,
			&i.AuthorizedUid,
			&i.RequestorToken,
			&i.Count,
			&i.Acceptor,
			&i.Status,
			&i.Topic,
			&i.Brief,
			&i.Created,
			&i.Accepted,
			&i.Closed,
			&i.ClosedBy,
			&i.CloseReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const TicketsRepositoryList3 = `-- name: TicketsRepositoryList3 :many
SELECT t.id, t.name, t.email, t.authorized, t.authorized_uid, t.requestor_token, t.count, t.acceptor, t.status, t.topic, t.brief, t.created, t.accepted, t.closed, t.closed_by, t.close_reason FROM tickets t WHERE t.authorized = $1 AND t.requestor_token = $2 ORDER BY t.created DESC
`

type TicketsRepositoryList3Params struct {
	Authorized     bool
	RequestorToken pgtype.Text
}

func (q *Queries) TicketsRepositoryList3(ctx context.Context, arg TicketsRepositoryList3Params) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, TicketsRepositoryList3, arg.Authorized, arg.RequestorToken)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Authorized,
			&i.AuthorizedUid,
			&i.RequestorToken,
			&i.Count,
			&i.Acceptor,
			&i.Status,
			&i.Topic,
			&i.Brief,
			&i.Created,
			&i.Accepted,
			&i.Closed,
			&i.ClosedBy,
			&i.CloseReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const TicketsRepositoryUser1 = `-- name: TicketsRepositoryUser1 :one
SELECT name, email FROM tickets WHERE requestor_token = $1
`

type TicketsRepositoryUser1Row struct {
	Name  pgtype.Text
	Email pgtype.Text
}

func (q *Queries) TicketsRepositoryUser1(ctx context.Context, requestorToken pgtype.Text) (TicketsRepositoryUser1Row, error) {
	row := q.db.QueryRow(ctx, TicketsRepositoryUser1, requestorToken)
	var i TicketsRepositoryUser1Row
	err := row.Scan(&i.Name, &i.Email)
	return i, err
}

const TicketsRepositoryUser2 = `-- name: TicketsRepositoryUser2 :one
SELECT name, email FROM tickets WHERE authorized_uid = $1
`

type TicketsRepositoryUser2Row struct {
	Name  pgtype.Text
	Email pgtype.Text
}

func (q *Queries) TicketsRepositoryUser2(ctx context.Context, authorizedUid pgtype.Int8) (TicketsRepositoryUser2Row, error) {
	row := q.db.QueryRow(ctx, TicketsRepositoryUser2, authorizedUid)
	var i TicketsRepositoryUser2Row
	err := row.Scan(&i.Name, &i.Email)
	return i, err
}

const UserRepositoryActivateRank1 = `-- name: UserRepositoryActivateRank1 :one
UPDATE rank_activations SET activated = $1, activated_by = $2 WHERE code = $3 RETURNING rank
`

type UserRepositoryActivateRank1Params struct {
	Activated   pgtype.Timestamptz
	ActivatedBy pgtype.Int8
	Code        pgtype.UUID
}

func (q *Queries) UserRepositoryActivateRank1(ctx context.Context, arg UserRepositoryActivateRank1Params) (string, error) {
	row := q.db.QueryRow(ctx, UserRepositoryActivateRank1, arg.Activated, arg.ActivatedBy, arg.Code)
	var rank string
	err := row.Scan(&rank)
	return rank, err
}

const UserRepositoryAddAvatar1 = `-- name: UserRepositoryAddAvatar1 :exec
INSERT INTO user_avatars (user_id, object_key, content_type, size_bytes, updated_at)
		VALUES ($1, $2, $3, $4, now())
		ON CONFLICT (user_id)
		DO UPDATE SET
			object_key = excluded.object_key,
			content_type = excluded.content_type,
			size_bytes = excluded.size_bytes,
			updated_at = now()
`

type UserRepositoryAddAvatar1Params struct {
	UserID      int64
	ObjectKey   string
	ContentType pgtype.Text
	SizeBytes   pgtype.Int8
}

func (q *Queries) UserRepositoryAddAvatar1(ctx context.Context, arg UserRepositoryAddAvatar1Params) error {
	_, err := q.db.Exec(ctx, UserRepositoryAddAvatar1,
		arg.UserID,
		arg.ObjectKey,
		arg.ContentType,
		arg.SizeBytes,
	)
	return err
}

const UserRepositoryAppendRecoveryCodes1 = `-- name: UserRepositoryAppendRecoveryCodes1 :exec
INSERT INTO users_recovery_codes (user_id, code_hash) VALUES ($1, $2)
`

type UserRepositoryAppendRecoveryCodes1Params struct {
	UserID   int64
	CodeHash string
}

func (q *Queries) UserRepositoryAppendRecoveryCodes1(ctx context.Context, arg UserRepositoryAppendRecoveryCodes1Params) error {
	_, err := q.db.Exec(ctx, UserRepositoryAppendRecoveryCodes1, arg.UserID, arg.CodeHash)
	return err
}

const UserRepositoryBan1 = `-- name: UserRepositoryBan1 :exec
INSERT INTO bans (executor, target, reason, expires) VALUES ($1, $2, $3, $4)
`

type UserRepositoryBan1Params struct {
	Executor int64
	Target   int64
	Reason   pgtype.Text
	Expires  pgtype.Timestamptz
}

func (q *Queries) UserRepositoryBan1(ctx context.Context, arg UserRepositoryBan1Params) error {
	_, err := q.db.Exec(ctx, UserRepositoryBan1,
		arg.Executor,
		arg.Target,
		arg.Reason,
		arg.Expires,
	)
	return err
}

const UserRepositoryBanInfo1 = `-- name: UserRepositoryBanInfo1 :one
SELECT b.id, b.executor, b.reason, b.at, b.expires FROM bans b WHERE b.target = $1
`

type UserRepositoryBanInfo1Row struct {
	ID       pgtype.UUID
	Executor int64
	Reason   pgtype.Text
	At       pgtype.Timestamptz
	Expires  pgtype.Timestamptz
}

func (q *Queries) UserRepositoryBanInfo1(ctx context.Context, target int64) (UserRepositoryBanInfo1Row, error) {
	row := q.db.QueryRow(ctx, UserRepositoryBanInfo1, target)
	var i UserRepositoryBanInfo1Row
	err := row.Scan(
		&i.ID,
		&i.Executor,
		&i.Reason,
		&i.At,
		&i.Expires,
	)
	return i, err
}

const UserRepositoryCanActivateCode1 = `-- name: UserRepositoryCanActivateCode1 :one
SELECT EXISTS (SELECT 1 FROM rank_activations WHERE activated_by = $1)
`

func (q *Queries) UserRepositoryCanActivateCode1(ctx context.Context, activatedBy pgtype.Int8) (bool, error) {
	row := q.db.QueryRow(ctx, UserRepositoryCanActivateCode1, activatedBy)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const UserRepositoryCanEdit1 = `-- name: UserRepositoryCanEdit1 :one
SELECT COALESCE(r1.weight, 0) > COALESCE(r2.weight, 0) AS can_edit FROM users u1 JOIN users u2 ON u2.uid = $2 LEFT JOIN ranks r1 ON r1.name = (u1.rank).name LEFT JOIN ranks r2 ON r2.name = (u2.rank).name WHERE u1.uid = $1
`

type UserRepositoryCanEdit1Params struct {
	Uid   int64
	Uid_2 int64
}

func (q *Queries) UserRepositoryCanEdit1(ctx context.Context, arg UserRepositoryCanEdit1Params) (bool, error) {
	row := q.db.QueryRow(ctx, UserRepositoryCanEdit1, arg.Uid, arg.Uid_2)
	var can_edit bool
	err := row.Scan(&can_edit)
	return can_edit, err
}

const UserRepositoryCascadeRecoveryCodes1 = `-- name: UserRepositoryCascadeRecoveryCodes1 :exec
DELETE FROM users_recovery_codes WHERE user_id = $1 AND code_hash = $2
`

type UserRepositoryCascadeRecoveryCodes1Params struct {
	UserID   int64
	CodeHash string
}

func (q *Queries) UserRepositoryCascadeRecoveryCodes1(ctx context.Context, arg UserRepositoryCascadeRecoveryCodes1Params) error {
	_, err := q.db.Exec(ctx, UserRepositoryCascadeRecoveryCodes1, arg.UserID, arg.CodeHash)
	return err
}

const UserRepositoryChangePerms1 = `-- name: UserRepositoryChangePerms1 :exec
UPDATE users u SET permissions = perm_set(u.permissions, $1, $2) WHERE u.uid = $3
`

type UserRepositoryChangePerms1Params struct {
	Perm  string
	State bool
	Uid   int64
}

func (q *Queries) UserRepositoryChangePerms1(ctx context.Context, arg UserRepositoryChangePerms1Params) error {
	_, err := q.db.Exec(ctx, UserRepositoryChangePerms1, arg.Perm, arg.State, arg.Uid)
	return err
}

const UserRepositoryCodeExists1 = `-- name: UserRepositoryCodeExists1 :one
SELECT EXISTS (SELECT 1 FROM rank_activations WHERE code = $1)
`

func (q *Queries) UserRepositoryCodeExists1(ctx context.Context, code pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, UserRepositoryCodeExists1, code)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const UserRepositoryDeleteAvatar1 = `-- name: UserRepositoryDeleteAvatar1 :exec
DELETE FROM user_avatars WHERE user_id = $1
`

func (q *Queries) UserRepositoryDeleteAvatar1(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, UserRepositoryDeleteAvatar1, userID)
	return err
}

const UserRepositoryDeleteProfile1 = `-- name: UserRepositoryDeleteProfile1 :exec
DELETE FROM users WHERE uid = $1
`

func (q *Queries) UserRepositoryDeleteProfile1(ctx context.Context, uid int64) error {
	_, err := q.db.Exec(ctx, UserRepositoryDeleteProfile1, uid)
	return err
}

const UserRepositoryGetAvatar1 = `-- name: UserRepositoryGetAvatar1 :one
SELECT a.object_key, a.content_type, a.size_bytes, a.updated_at
		FROM user_avatars a
		WHERE a.user_id = $1
`

type UserRepositoryGetAvatar1Row struct {
	ObjectKey   string
	ContentType pgtype.Text
	SizeBytes   pgtype.Int8
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) UserRepositoryGetAvatar1(ctx context.Context, userID int64) (UserRepositoryGetAvatar1Row, error) {
	row := q.db.QueryRow(ctx, UserRepositoryGetAvatar1, userID)
	var i UserRepositoryGetAvatar1Row
	err := row.Scan(
		&i.ObjectKey,
		&i.ContentType,
		&i.SizeBytes,
		&i.UpdatedAt,
	)
	return i, err
}

const UserRepositoryGetEmail1 = `-- name: UserRepositoryGetEmail1 :one
SELECT (u.email).address, (u.email).verified FROM users u WHERE u.uid = $1
`

type UserRepositoryGetEmail1Row struct {
	Column1 interface{}
	Column2 interface{}
}

func (q *Queries) UserRepositoryGetEmail1(ctx context.Context, uid int64) (UserRepositoryGetEmail1Row, error) {
	row := q.db.QueryRow(ctx, UserRepositoryGetEmail1, uid)
	var i UserRepositoryGetEmail1Row
	err := row.Scan(&i.Column1, &i.Column2)
	return i, err
}

const UserRepositoryGetJoinedAT1 = `-- name: UserRepositoryGetJoinedAT1 :one
SELECT u.joined FROM users u WHERE u.uid = $1
`

func (q *Queries) UserRepositoryGetJoinedAT1(ctx context.Context, uid int64) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, UserRepositoryGetJoinedAT1, uid)
	var joined pgtype.Timestamptz
	err := row.Scan(&joined)
	return joined, err
}

const UserRepositoryGetList1 = `-- name: UserRepositoryGetList1 :many

SELECT u.uid, u.username, (u.email).address, (u.email).verified, (u.rank).name, (u.rank).expires, u.joined FROM users u ORDER BY u.joined
`

type UserRepositoryGetList1Row struct {
	Uid      int64
	Username string
	Column3  interface{}
	Column4  interface{}
	Column5  interface{}
	Column6  interface{}
	Joined   pgtype.Timestamptz
}

// Code generated by migrate_sqlc_queries.go. DO NOT EDIT.
func (q *Queries) UserRepositoryGetList1(ctx context.Context) ([]UserRepositoryGetList1Row, error) {
	rows, err := q.db.Query(ctx, UserRepositoryGetList1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserRepositoryGetList1Row
	for rows.Next() {
		var i UserRepositoryGetList1Row
		if err := rows.Scan(
			&i.Uid,
			&i.Username,
			&i.Column3,
			&i.Column4,
			&i.Column5,
			&i.Column6,
			&i.Joined,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UserRepositoryGetPendingTOTP1 = `-- name: UserRepositoryGetPendingTOTP1 :one
SELECT totp_pending_secret FROM users WHERE uid = $1
`

func (q *Queries) UserRepositoryGetPendingTOTP1(ctx context.Context, uid int64) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, UserRepositoryGetPendingTOTP1, uid)
	var totp_pending_secret pgtype.Text
	err := row.Scan(&totp_pending_secret)
	return totp_pending_secret, err
}

const UserRepositoryGetRank1 = `-- name: UserRepositoryGetRank1 :one
SELECT (u.rank).name, (u.rank).expires FROM users u WHERE u.uid = $1
`

type UserRepositoryGetRank1Row struct {
	Column1 interface{}
	Column2 interface{}
}

func (q *Queries) UserRepositoryGetRank1(ctx context.Context, uid int64) (UserRepositoryGetRank1Row, error) {
	row := q.db.QueryRow(ctx, UserRepositoryGetRank1, uid)
	var i UserRepositoryGetRank1Row
	err := row.Scan(&i.Column1, &i.Column2)
	return i, err
}

const UserRepositoryGetRecoveryCodes1 = `-- name: UserRepositoryGetRecoveryCodes1 :many
SELECT code_hash FROM users_recovery_codes WHERE user_id = $1
`

func (q *Queries) UserRepositoryGetRecoveryCodes1(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, UserRepositoryGetRecoveryCodes1, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var code_hash string
		if err := rows.Scan(&code_hash); err != nil {
			return nil, err
		}
		items = append(items, code_hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UserRepositoryGetSettings1 = `-- name: UserRepositoryGetSettings1 :one
SELECT (u.settings).session_live_time, (u.settings).display_name, (u.settings).description FROM users u WHERE u.uid = $1
`

type UserRepositoryGetSettings1Row struct {
	Column1 interface{}
	Column2 interface{}
	Column3 interface{}
}

func (q *Queries) UserRepositoryGetSettings1(ctx context.Context, uid int64) (UserRepositoryGetSettings1Row, error) {
	row := q.db.QueryRow(ctx, UserRepositoryGetSettings1, uid)
	var i UserRepositoryGetSettings1Row
	err := row.Scan(&i.Column1, &i.Column2, &i.Column3)
	return i, err
}

const UserRepositoryGetTOTPLastStep1 = `-- name: UserRepositoryGetTOTPLastStep1 :one
SELECT totp_last_step FROM users WHERE uid = $1
`

func (q *Queries) UserRepositoryGetTOTPLastStep1(ctx context.Context, uid int64) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, UserRepositoryGetTOTPLastStep1, uid)
	var totp_last_step pgtype.Int8
	err := row.Scan(&totp_last_step)
	return totp_last_step, err
}

const UserRepositoryGetTOTPSecret1 = `-- name: UserRepositoryGetTOTPSecret1 :one
SELECT totp_secret FROM users WHERE uid = $1
`

func (q *Queries) UserRepositoryGetTOTPSecret1(ctx context.Context, uid int64) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, UserRepositoryGetTOTPSecret1, uid)
	var totp_secret pgtype.Text
	err := row.Scan(&totp_secret)
	return totp_secret, err
}

const UserRepositoryGetUID1 = `-- name: UserRepositoryGetUID1 :one
SELECT u.uid FROM users u WHERE u.username = $1
`

func (q *Queries) UserRepositoryGetUID1(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRow(ctx, UserRepositoryGetUID1, username)
	var uid int64
	err := row.Scan(&uid)
	return uid, err
}

const UserRepositoryGetUserLastActive1 = `-- name: UserRepositoryGetUserLastActive1 :one
SELECT at
        FROM events
        WHERE actor_type = 'User' AND actor_id = $1
        ORDER BY at DESC, id DESC
        LIMIT 1
`

func (q *Queries) UserRepositoryGetUserLastActive1(ctx context.Context, actorID pgtype.Int8) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, UserRepositoryGetUserLastActive1, actorID)
	var at pgtype.Timestamptz
	err := row.Scan(&at)
	return at, err
}

const UserRepositoryGetUserSessionLiveTime1 = `-- name: UserRepositoryGetUserSessionLiveTime1 :one
SELECT (u.settings).session_live_time FROM users u WHERE u.uid = $1
`

func (q *Queries) UserRepositoryGetUserSessionLiveTime1(ctx context.Context, uid int64) (interface{}, error) {
	row := q.db.QueryRow(ctx, UserRepositoryGetUserSessionLiveTime1, uid)
	var column_1 interface{}
	err := row.Scan(&column_1)
	return column_1, err
}

const UserRepositoryGetUsername1 = `-- name: UserRepositoryGetUsername1 :one
SELECT u.username FROM users u WHERE u.uid = $1
`

func (q *Queries) UserRepositoryGetUsername1(ctx context.Context, uid int64) (string, error) {
	row := q.db.QueryRow(ctx, UserRepositoryGetUsername1, uid)
	var username string
	err := row.Scan(&username)
	return username, err
}

const UserRepositoryHasPerm1 = `-- name: UserRepositoryHasPerm1 :one
SELECT CASE
			WHEN (u.rank).name = 'root' THEN true
			ELSE perm_allowed(u.permissions, $1)
		END
		FROM users u
		WHERE u.uid = $2
`

type UserRepositoryHasPerm1Params struct {
	Perm string
	Uid  int64
}

func (q *Queries) UserRepositoryHasPerm1(ctx context.Context, arg UserRepositoryHasPerm1Params) (interface{}, error) {
	row := q.db.QueryRow(ctx, UserRepositoryHasPerm1, arg.Perm, arg.Uid)
	var column_1 interface{}
	err := row.Scan(&column_1)
	return column_1, err
}

const UserRepositoryIsBanned1 = `-- name: UserRepositoryIsBanned1 :one
SELECT EXISTS (SELECT 1 FROM bans b WHERE b.target = $1)
`

func (q *Queries) UserRepositoryIsBanned1(ctx context.Context, target int64) (bool, error) {
	row := q.db.QueryRow(ctx, UserRepositoryIsBanned1, target)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const UserRepositoryIsExists1 = `-- name: UserRepositoryIsExists1 :one
SELECT EXISTS (SELECT 1 FROM users u WHERE u.username = $1 OR (u.email).address = $2 OR u.uid = $3)
`

type UserRepositoryIsExists1Params struct {
	Username string
	Email    string
	Uid      int64
}

func (q *Queries) UserRepositoryIsExists1(ctx context.Context, arg UserRepositoryIsExists1Params) (bool, error) {
	row := q.db.QueryRow(ctx, UserRepositoryIsExists1, arg.Username, arg.Email, arg.Uid)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const UserRepositoryIsTOTPEnabled1 = `-- name: UserRepositoryIsTOTPEnabled1 :one
SELECT totp_enabled FROM users WHERE uid = $1
`

func (q *Queries) UserRepositoryIsTOTPEnabled1(ctx context.Context, uid int64) (bool, error) {
	row := q.db.QueryRow(ctx, UserRepositoryIsTOTPEnabled1, uid)
	var totp_enabled bool
	err := row.Scan(&totp_enabled)
	return totp_enabled, err
}

const UserRepositoryIsTOTPending1 = `-- name: UserRepositoryIsTOTPending1 :one
SELECT totp_pending_secret IS NOT NULL FROM users WHERE uid = $1
`

func (q *Queries) UserRepositoryIsTOTPending1(ctx context.Context, uid int64) (interface{}, error) {
	row := q.db.QueryRow(ctx, UserRepositoryIsTOTPending1, uid)
	var column_1 interface{}
	err := row.Scan(&column_1)
	return column_1, err
}

const UserRepositoryIsValidRecovery1 = `-- name: UserRepositoryIsValidRecovery1 :many
SELECT code_hash
		 FROM users_recovery_codes
		 WHERE user_id = $1
`

func (q *Queries) UserRepositoryIsValidRecovery1(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, UserRepositoryIsValidRecovery1, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var code_hash string
		if err := rows.Scan(&code_hash); err != nil {
			return nil, err
		}
		items = append(items, code_hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UserRepositoryPerms1 = `-- name: UserRepositoryPerms1 :one
SELECT CASE
			WHEN (u.rank).name = 'root' THEN COALESCE(to_jsonb(r.permissions), to_jsonb(u.permissions))
			ELSE to_jsonb(u.permissions)
		END
		FROM users u
		LEFT JOIN ranks r ON r.name = (u.rank).name
		WHERE u.uid = $1
`

func (q *Queries) UserRepositoryPerms1(ctx context.Context, uid int64) (interface{}, error) {
	row := q.db.QueryRow(ctx, UserRepositoryPerms1, uid)
	var column_1 interface{}
	err := row.Scan(&column_1)
	return column_1, err
}

const UserRepositoryResetTOTP1 = `-- name: UserRepositoryResetTOTP1 :exec
UPDATE users SET totp_enabled = false, totp_secret = NULL, totp_pending_secret = NULL, totp_confirmed_at = NULL, totp_last_step = NULL, totp_pending_created_at = NULL WHERE uid = $1
`

func (q *Queries) UserRepositoryResetTOTP1(ctx context.Context, uid int64) error {
	_, err := q.db.Exec(ctx, UserRepositoryResetTOTP1, uid)
	return err
}

const UserRepositorySetCodeUsed1 = `-- name: UserRepositorySetCodeUsed1 :exec
UPDATE users_recovery_codes SET used_at = $1 WHERE code_hash = $2
`

type UserRepositorySetCodeUsed1Params struct {
	UsedAt   pgtype.Timestamptz
	CodeHash string
}

func (q *Queries) UserRepositorySetCodeUsed1(ctx context.Context, arg UserRepositorySetCodeUsed1Params) error {
	_, err := q.db.Exec(ctx, UserRepositorySetCodeUsed1, arg.UsedAt, arg.CodeHash)
	return err
}

const UserRepositorySetConfirmed1 = `-- name: UserRepositorySetConfirmed1 :exec
UPDATE users SET totp_enabled = true, totp_secret = totp_pending_secret, totp_pending_secret = NULL, totp_last_step = NULL, totp_confirmed_at = now(), totp_pending_created_at = NULL WHERE uid = $1
`

func (q *Queries) UserRepositorySetConfirmed1(ctx context.Context, uid int64) error {
	_, err := q.db.Exec(ctx, UserRepositorySetConfirmed1, uid)
	return err
}

const UserRepositorySetEmailVerifiedByAddress1 = `-- name: UserRepositorySetEmailVerifiedByAddress1 :exec
UPDATE users u
		SET email = ROW((u.email).address, $2)::users_email_t
		WHERE lower((u.email).address) = lower($1)
`

type UserRepositorySetEmailVerifiedByAddress1Params struct {
	Lower   string
	Column2 string
}

func (q *Queries) UserRepositorySetEmailVerifiedByAddress1(ctx context.Context, arg UserRepositorySetEmailVerifiedByAddress1Params) error {
	_, err := q.db.Exec(ctx, UserRepositorySetEmailVerifiedByAddress1, arg.Lower, arg.Column2)
	return err
}

const UserRepositorySetPendingTOTP1 = `-- name: UserRepositorySetPendingTOTP1 :exec
UPDATE users SET totp_pending_secret = $1, totp_pending_created_at = $2 WHERE uid = $3
`

type UserRepositorySetPendingTOTP1Params struct {
	TotpPendingSecret    pgtype.Text
	TotpPendingCreatedAt pgtype.Timestamptz
	Uid                  int64
}

func (q *Queries) UserRepositorySetPendingTOTP1(ctx context.Context, arg UserRepositorySetPendingTOTP1Params) error {
	_, err := q.db.Exec(ctx, UserRepositorySetPendingTOTP1, arg.TotpPendingSecret, arg.TotpPendingCreatedAt, arg.Uid)
	return err
}

const UserRepositorySetRank1 = `-- name: UserRepositorySetRank1 :exec
UPDATE users SET rank = ROW($1, NULL)::users_rank_t WHERE uid = $2
`

type UserRepositorySetRank1Params struct {
	Column1 string
	Uid     int64
}

func (q *Queries) UserRepositorySetRank1(ctx context.Context, arg UserRepositorySetRank1Params) error {
	_, err := q.db.Exec(ctx, UserRepositorySetRank1, arg.Column1, arg.Uid)
	return err
}

const UserRepositorySetRank2 = `-- name: UserRepositorySetRank2 :exec
UPDATE users SET rank = ROW($1, $2)::users_rank_t WHERE uid = $3
`

type UserRepositorySetRank2Params struct {
	Column1 string
	Column2 string
	Uid     int64
}

func (q *Queries) UserRepositorySetRank2(ctx context.Context, arg UserRepositorySetRank2Params) error {
	_, err := q.db.Exec(ctx, UserRepositorySetRank2, arg.Column1, arg.Column2, arg.Uid)
	return err
}

const UserRepositorySetTOTPLastStep1 = `-- name: UserRepositorySetTOTPLastStep1 :exec
UPDATE users SET totp_last_step = $1 WHERE uid = $2
`

type UserRepositorySetTOTPLastStep1Params struct {
	TotpLastStep pgtype.Int8
	Uid          int64
}

func (q *Queries) UserRepositorySetTOTPLastStep1(ctx context.Context, arg UserRepositorySetTOTPLastStep1Params) error {
	_, err := q.db.Exec(ctx, UserRepositorySetTOTPLastStep1, arg.TotpLastStep, arg.Uid)
	return err
}

const UserRepositoryUnBan1 = `-- name: UserRepositoryUnBan1 :exec
DELETE FROM bans b WHERE b.target = $1
`

func (q *Queries) UserRepositoryUnBan1(ctx context.Context, target int64) error {
	_, err := q.db.Exec(ctx, UserRepositoryUnBan1, target)
	return err
}

const UserRepositoryUpdateDescription1 = `-- name: UserRepositoryUpdateDescription1 :exec
UPDATE users u
		SET settings = ROW((u.settings).display_name, $1, (u.settings).avatar, (u.settings).session_live_time)::user_settings_t
		WHERE u.uid = $2
`

type UserRepositoryUpdateDescription1Params struct {
	Column1 string
	Uid     int64
}

func (q *Queries) UserRepositoryUpdateDescription1(ctx context.Context, arg UserRepositoryUpdateDescription1Params) error {
	_, err := q.db.Exec(ctx, UserRepositoryUpdateDescription1, arg.Column1, arg.Uid)
	return err
}

const UserRepositoryUpdateDisplayName1 = `-- name: UserRepositoryUpdateDisplayName1 :exec
UPDATE users u
		SET settings = ROW($1, (u.settings).description, (u.settings).avatar, (u.settings).session_live_time)::user_settings_t
		WHERE u.uid = $2
`

type UserRepositoryUpdateDisplayName1Params struct {
	Column1 string
	Uid     int64
}

func (q *Queries) UserRepositoryUpdateDisplayName1(ctx context.Context, arg UserRepositoryUpdateDisplayName1Params) error {
	_, err := q.db.Exec(ctx, UserRepositoryUpdateDisplayName1, arg.Column1, arg.Uid)
	return err
}

const UserRepositoryUpdatePasswordByEmail1 = `-- name: UserRepositoryUpdatePasswordByEmail1 :exec
UPDATE users u
		SET password = $2
		WHERE lower((u.email).address) = lower($1)
`

type UserRepositoryUpdatePasswordByEmail1Params struct {
	Lower    string
	Password pgtype.Text
}

func (q *Queries) UserRepositoryUpdatePasswordByEmail1(ctx context.Context, arg UserRepositoryUpdatePasswordByEmail1Params) error {
	_, err := q.db.Exec(ctx, UserRepositoryUpdatePasswordByEmail1, arg.Lower, arg.Password)
	return err
}

const VerificationRepositoryBanEmail1 = `-- name: VerificationRepositoryBanEmail1 :exec
INSERT INTO banned_emails (email, reason) VALUES ($1, $2)
`

type VerificationRepositoryBanEmail1Params struct {
	Email  string
	Reason string
}

func (q *Queries) VerificationRepositoryBanEmail1(ctx context.Context, arg VerificationRepositoryBanEmail1Params) error {
	_, err := q.db.Exec(ctx, VerificationRepositoryBanEmail1, arg.Email, arg.Reason)
	return err
}

const VerificationRepositoryConsume1 = `-- name: VerificationRepositoryConsume1 :exec
UPDATE auth_action_tokens SET used_at = $1 WHERE token_hash = $2 AND purpose = $3 AND used_at IS NULL
`

type VerificationRepositoryConsume1Params struct {
	UsedAt    pgtype.Timestamptz
	TokenHash []byte
	Purpose   VerificationPurpose
}

func (q *Queries) VerificationRepositoryConsume1(ctx context.Context, arg VerificationRepositoryConsume1Params) error {
	_, err := q.db.Exec(ctx, VerificationRepositoryConsume1, arg.UsedAt, arg.TokenHash, arg.Purpose)
	return err
}

const VerificationRepositoryCreate1 = `-- name: VerificationRepositoryCreate1 :exec
INSERT INTO auth_action_tokens (email, purpose, token_hash, expires_at, ip, user_agent, created_at)
		VALUES ($1, $2, $3, $4, $5, $6, $7)
		ON CONFLICT (email, purpose) WHERE used_at IS NULL
		DO UPDATE SET
			token_hash = EXCLUDED.token_hash,
			expires_at = EXCLUDED.expires_at,
			ip = EXCLUDED.ip,
			user_agent = EXCLUDED.user_agent,
			created_at = EXCLUDED.created_at,
			used_at = NULL
`

type VerificationRepositoryCreate1Params struct {
	Email     string
	Purpose   VerificationPurpose
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
	Ip        *netip.Addr
	UserAgent pgtype.Text
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) VerificationRepositoryCreate1(ctx context.Context, arg VerificationRepositoryCreate1Params) error {
	_, err := q.db.Exec(ctx, VerificationRepositoryCreate1,
		arg.Email,
		arg.Purpose,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
		arg.CreatedAt,
	)
	return err
}

const VerificationRepositoryEmailExists1 = `-- name: VerificationRepositoryEmailExists1 :one
SELECT EXISTS (SELECT 1 FROM users WHERE (email).address = $1)
`

func (q *Queries) VerificationRepositoryEmailExists1(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, VerificationRepositoryEmailExists1, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const VerificationRepositoryGetRecord1 = `-- name: VerificationRepositoryGetRecord1 :one
SELECT id, email, purpose, expires_at, used_at FROM auth_action_tokens WHERE token_hash = $1 AND purpose = $2
`

type VerificationRepositoryGetRecord1Params struct {
	TokenHash []byte
	Purpose   VerificationPurpose
}

type VerificationRepositoryGetRecord1Row struct {
	ID        int64
	Email     string
	Purpose   VerificationPurpose
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
}

func (q *Queries) VerificationRepositoryGetRecord1(ctx context.Context, arg VerificationRepositoryGetRecord1Params) (VerificationRepositoryGetRecord1Row, error) {
	row := q.db.QueryRow(ctx, VerificationRepositoryGetRecord1, arg.TokenHash, arg.Purpose)
	var i VerificationRepositoryGetRecord1Row
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Purpose,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const VerificationRepositoryIsBanned1 = `-- name: VerificationRepositoryIsBanned1 :one
SELECT EXISTS (SELECT 1 FROM banned_emails WHERE email = $1)
`

func (q *Queries) VerificationRepositoryIsBanned1(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, VerificationRepositoryIsBanned1, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
