# To build all images (including build-only services) use:
# docker compose --profile build-only -f docker-compose.yml -f docker-compose.build.yml build
services:
  aesterial_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ivanskem/aesterial-jcup:backend-latest

  aesterial_frontend:
    build:
      context: ./frontend/web
      dockerfile: Dockerfile
    image: ivanskem/aesterial-jcup:frontend-latest

  aesterial_backend_mail:
    build:
      context: ./backend/mail-proxy
      dockerfile: Dockerfile
    image: aesterial_backend_mail:latest
