version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?set POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [appnet]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    image: ivanskem/aesterial-jcup:backend-latest
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-app}?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    networks: [appnet]
    expose:
      - "8080"
      - "9090"

  frontend:
    image: ivanskem/aesterial-jcup:frontend-latest
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: "3000"
      NODE_OPTIONS: "--max-old-space-size=512"
    networks: [appnet]
    expose:
      - "3000"
    depends_on:
      - backend

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      # если домена/https пока нет — можешь временно убрать 443
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks: [appnet]
    depends_on:
      - frontend
      - backend

networks:
  appnet:

volumes:
  pgdata:
  caddy_data:
  caddy_config:
