-- Code generated by migrate_sqlc_queries.go. DO NOT EDIT.

-- name: UserRepositoryGetList1 :many
SELECT u.uid, u.username, (u.email).address, (u.email).verified, (u.rank).name, (u.rank).expires, u.joined FROM users u ORDER BY u.joined;

-- name: UserRepositoryGetUID1 :one
SELECT u.uid FROM users u WHERE u.username = $1;

-- name: UserRepositoryGetUsername1 :one
SELECT u.username FROM users u WHERE u.uid = $1;

-- name: UserRepositoryGetEmail1 :one
SELECT (u.email).address, (u.email).verified FROM users u WHERE u.uid = $1;

-- name: UserRepositoryGetRank1 :one
SELECT (u.rank).name, (u.rank).expires FROM users u WHERE u.uid = $1;

-- name: UserRepositoryGetJoinedAT1 :one
SELECT u.joined FROM users u WHERE u.uid = $1;

-- name: UserRepositoryGetUserLastActive1 :one
SELECT at
        FROM events
        WHERE actor_type = 'User' AND actor_id = $1
        ORDER BY at DESC, id DESC
        LIMIT 1;

-- name: UserRepositoryGetSettings1 :one
SELECT (u.settings).session_live_time, (u.settings).display_name, (u.settings).description FROM users u WHERE u.uid = $1;

-- name: UserRepositoryGetUserSessionLiveTime1 :one
SELECT (u.settings).session_live_time FROM users u WHERE u.uid = $1;

-- name: UserRepositoryGetAvatar1 :one
SELECT a.object_key, a.content_type, a.size_bytes, a.updated_at
		FROM user_avatars a
		WHERE a.user_id = $1;

-- name: UserRepositoryIsExists1 :one
SELECT EXISTS (SELECT 1 FROM users u WHERE u.username = $1 OR (u.email).address = $2 OR u.uid = $3);

-- name: UserRepositoryUpdateDisplayName1 :exec
UPDATE users u
		SET settings = ROW($1, (u.settings).description, (u.settings).avatar, (u.settings).session_live_time)::user_settings_t
		WHERE u.uid = $2;

-- name: UserRepositoryUpdateDescription1 :exec
UPDATE users u
		SET settings = ROW((u.settings).display_name, $1, (u.settings).avatar, (u.settings).session_live_time)::user_settings_t
		WHERE u.uid = $2;

-- name: UserRepositorySetEmailVerifiedByAddress1 :exec
UPDATE users u
		SET email = ROW((u.email).address, $2)::users_email_t
		WHERE lower((u.email).address) = lower($1);

-- name: UserRepositoryUpdatePasswordByEmail1 :exec
UPDATE users u
		SET password = $2
		WHERE lower((u.email).address) = lower($1);

-- name: UserRepositoryIsBanned1 :one
SELECT EXISTS (SELECT 1 FROM bans b WHERE b.target = $1);

-- name: UserRepositoryBan1 :exec
INSERT INTO bans (executor, target, reason, expires) VALUES ($1, $2, $3, $4);

-- name: UserRepositoryUnBan1 :exec
DELETE FROM bans b WHERE b.target = $1;

-- name: UserRepositoryBanInfo1 :one
SELECT b.id, b.executor, b.reason, b.at, b.expires FROM bans b WHERE b.target = $1;

-- name: UserRepositoryAddAvatar1 :exec
INSERT INTO user_avatars (user_id, object_key, content_type, size_bytes, updated_at)
		VALUES ($1, $2, $3, $4, now())
		ON CONFLICT (user_id)
		DO UPDATE SET
			object_key = excluded.object_key,
			content_type = excluded.content_type,
			size_bytes = excluded.size_bytes,
			updated_at = now();

-- name: UserRepositoryDeleteAvatar1 :exec
DELETE FROM user_avatars WHERE user_id = $1;

-- name: UserRepositoryHasPerm1 :one
SELECT CASE
			WHEN (u.rank).name = 'root' THEN true
			ELSE perm_allowed(u.permissions, $1)
		END
		FROM users u
		WHERE u.uid = $2;

-- name: UserRepositoryPerms1 :one
SELECT CASE
			WHEN (u.rank).name = 'root' THEN COALESCE(to_jsonb(r.permissions), to_jsonb(u.permissions))
			ELSE to_jsonb(u.permissions)
		END
		FROM users u
		LEFT JOIN ranks r ON r.name = (u.rank).name
		WHERE u.uid = $1;

-- name: UserRepositoryChangePerms1 :exec
UPDATE users u SET permissions = perm_set(u.permissions, $1, $2) WHERE u.uid = $3;

-- name: UserRepositoryDeleteProfile1 :exec
DELETE FROM users WHERE uid = $1;

-- name: UserRepositoryIsTOTPEnabled1 :one
SELECT totp_enabled FROM users WHERE uid = $1;

-- name: UserRepositoryGetPendingTOTP1 :one
SELECT totp_pending_secret FROM users WHERE uid = $1;

-- name: UserRepositorySetPendingTOTP1 :exec
UPDATE users SET totp_pending_secret = $1, totp_pending_created_at = $2 WHERE uid = $3;

-- name: UserRepositorySetConfirmed1 :exec
UPDATE users SET totp_enabled = true, totp_secret = totp_pending_secret, totp_pending_secret = NULL, totp_last_step = NULL, totp_confirmed_at = now(), totp_pending_created_at = NULL WHERE uid = $1;

-- name: UserRepositoryAppendRecoveryCodes1 :exec
INSERT INTO users_recovery_codes (user_id, code_hash) VALUES ($1, $2);

-- name: UserRepositoryCascadeRecoveryCodes1 :exec
DELETE FROM users_recovery_codes WHERE user_id = $1 AND code_hash = $2;

-- name: UserRepositoryGetRecoveryCodes1 :many
SELECT code_hash FROM users_recovery_codes WHERE user_id = $1;

-- name: UserRepositorySetCodeUsed1 :exec
UPDATE users_recovery_codes SET used_at = $1 WHERE code_hash = $2;

-- name: UserRepositoryResetTOTP1 :exec
UPDATE users SET totp_enabled = false, totp_secret = NULL, totp_pending_secret = NULL, totp_confirmed_at = NULL, totp_last_step = NULL, totp_pending_created_at = NULL WHERE uid = $1;

-- name: UserRepositoryIsValidRecovery1 :many
SELECT code_hash
		 FROM users_recovery_codes
		 WHERE user_id = $1;

-- name: UserRepositoryIsTOTPending1 :one
SELECT totp_pending_secret IS NOT NULL FROM users WHERE uid = $1;

-- name: UserRepositoryGetTOTPSecret1 :one
SELECT totp_secret FROM users WHERE uid = $1;

-- name: UserRepositoryGetTOTPLastStep1 :one
SELECT totp_last_step FROM users WHERE uid = $1;

-- name: UserRepositorySetTOTPLastStep1 :exec
UPDATE users SET totp_last_step = $1 WHERE uid = $2;

-- name: UserRepositoryCanEdit1 :one
SELECT COALESCE(r1.weight, 0) > COALESCE(r2.weight, 0) AS can_edit FROM users u1 JOIN users u2 ON u2.uid = $2 LEFT JOIN ranks r1 ON r1.name = (u1.rank).name LEFT JOIN ranks r2 ON r2.name = (u2.rank).name WHERE u1.uid = $1;

-- name: UserRepositoryCodeExists1 :one
SELECT EXISTS (SELECT 1 FROM rank_activations WHERE code = $1);

-- name: UserRepositoryCanActivateCode1 :one
SELECT EXISTS (SELECT 1 FROM rank_activations WHERE activated_by = $1);

-- name: UserRepositoryActivateRank1 :one
UPDATE rank_activations SET activated = $1, activated_by = $2 WHERE code = $3 RETURNING rank;

-- name: LoggerRepositoryAppend1 :exec
INSERT INTO events(event_type, level, message, actor_type, actor_id, trace_id, result) VALUES ($1, $2, $3, $4, $5, $6, $7);

-- name: LoggerRepositoryGetList1 :many
SELECT * FROM events ORDER BY at LIMIT $1 OFFSET $2;

-- name: LoggerRepositoryGetList2 :many
SELECT * FROM events ORDER BY at OFFSET $1;

-- name: LoginRepositoryRegister1 :one
INSERT INTO users (username, email, password)
		VALUES (
		$1,
		ROW($2, false)::users_email_t,
		$3) RETURNING uid;

-- name: LoginRepositoryAuthorization1 :one
SELECT u.uid FROM users u WHERE u.username = $1;

-- name: LoginRepositoryAuthorization2 :one
SELECT u.uid FROM users u WHERE (u.email).address = $1;

-- name: LoginRepositoryAuthorization3 :one
SELECT u.password FROM users u WHERE u.uid = $1;

-- name: LoginRepositoryGetUIDByEmail1 :one
SELECT u.uid FROM users u WHERE lower((u.email).address) = lower($1);

-- name: LoginRepositoryGetOAuthUID1 :one
SELECT uid FROM oauth WHERE service = $1 AND linked_id = $2;

-- name: LoginRepositoryLinkOAuth1 :exec
INSERT INTO oauth (uid, service, linked_id)
		VALUES ($1, $2, $3)
		ON CONFLICT (service, uid)
		DO UPDATE SET linked_id = EXCLUDED.linked_id;

-- name: LoginRepositoryLogout1 :exec
UPDATE sessions SET revoked = true WHERE id = $1;

-- name: SessionsRepositoryGetSession1 :one
SELECT * FROM sessions s WHERE s.id = $1;

-- name: SessionsRepositoryGetSessions1 :many
SELECT id FROM sessions s WHERE s.uid = $1 AND s.revoked = false AND s.expires > NOW() ORDER BY s.last_seen_at DESC NULLS LAST, s.created_at DESC;

-- name: SessionsRepositoryGetUID1 :one
SELECT uid FROM sessions s WHERE s.id = $1;

-- name: SessionsRepositorySetRevoked1 :exec
UPDATE sessions SET revoked = true WHERE id = $1;

-- name: SessionsRepositoryResetMFAs1 :exec
UPDATE sessions SET mfa_complete = false WHERE uid = $1;

-- name: SessionsRepositorySetMFACompleted1 :exec
UPDATE sessions SET mfa_complete = true WHERE id = $1;

-- name: SessionsRepositoryAddSession1 :exec
INSERT INTO sessions (id, uid, expires, user_agent_hash) VALUES ($1,$2, $3, $4);

-- name: SessionsRepositoryUpdateLastSeen1 :exec
UPDATE sessions SET last_seen_at = $1 WHERE id = $2;

-- name: GetProjectPhotos1 :many
SELECT p.object_key, p.content_type, p.size_bytes, p.created_at
		FROM project_photos p
		WHERE p.project_id = $1
		ORDER BY p.created_at;

-- name: GetWhoLikedProject1 :many
SELECT u.uid, u.username, u.joined FROM project_likes l JOIN users u ON u.uid = l.user_uid WHERE l.project_id = $1 ORDER BY l.created_at DESC LIMIT $2 OFFSET $3;

-- name: GetProject1 :one
SELECT p.id, p.author_uid, (p.info).title, (p.info).description, (p.info).category, ((p.info).location).city, ((p.info).location).latitude, ((p.info).location).longitude, ((p.info).location).address, p.likes_count, p.created_at, p.status FROM projects p WHERE p.id = $1;

-- name: ProjectsRepositoryGetProjectsByUID1 :many
SELECT p.id FROM projects p WHERE p.author_uid = $1;

-- name: ProjectsRepositoryCreateProject1 :one
INSERT INTO projects (author_uid, info) VALUES ($1, ROW($2, $3, $4::project_categories, ROW($5, $6, $7, $8)::project_location_t)::project_info_t) RETURNING id;

-- name: ProjectsRepositoryCreateProject3 :exec
INSERT INTO submissions (project_id) VALUES ($1);

-- name: ProjectsRepositoryCreateProject2 :exec
INSERT INTO project_photos (project_id, object_key, content_type, size_bytes, created_at)
		VALUES ($1, $2, $3, $4, now())
		ON CONFLICT (object_key) DO NOTHING;

-- name: ProjectsRepositoryToggleLike1 :one
select toggle_project_like($1::uuid, $2::bigint);

-- name: ProjectsRepositoryMessages1 :one
SELECT EXISTS(SELECT 1 FROM projects WHERE id = $1);

-- name: ProjectsRepositoryMessages2 :many
SELECT
			id,
			project_id,
			author_uid,
			content,
			reply_to_id,
			at
		FROM project_messages
		WHERE project_id = $1
		ORDER BY at ASC, id ASC;

-- name: ProjectsRepositoryCreateMessage1 :one
SELECT EXISTS(SELECT 1 FROM projects WHERE id = $1);

-- name: ProjectsRepositoryCreateMessage2 :one
SELECT EXISTS(SELECT 1 FROM project_messages WHERE project_id = $1 AND id = $2);

-- name: ProjectsRepositoryCreateMessage3 :exec
INSERT INTO project_messages (project_id, author_uid, content, reply_to_id) VALUES ($1, $2, $3, $4);

-- name: StatisticsRepositoryVoteCount1 :one
SELECT COUNT(*) FROM project_likes WHERE created_at >= $1;

-- name: StatisticsRepositoryGetOnlineUsers1 :one
SELECT COUNT(DISTINCT e.actor_id) FILTER ( WHERE e.actor_id != 0 )
		 FROM events e
		 WHERE e.at >= $1;

-- name: StatisticsRepositoryGetOfflineUsers1 :one
SELECT
		  (SELECT COUNT(*) FROM users)::bigint -
		  (SELECT COUNT(DISTINCT e.actor_id)  FILTER ( WHERE e.actor_id != 0 ) FROM events e WHERE e.at >= $1)::bigint;

-- name: StatisticsRepositoryNewIdeasCount1 :one
SELECT COUNT(*) FROM projects WHERE created_at >= $1;

-- name: StatisticsRepositorySaveStatisticsRecap1 :exec
INSERT INTO statistics_recap (at, us_activity, new_ideas, vote_count) VALUES ($1, ROW($2, $3)::users_activity_t, $4, $5);

-- name: StatisticsRepositoryStatisticsRecap1 :many
SELECT
			s.id,
			s.at,
			(s.us_activity).online,
			(s.us_activity).offline,
			s.new_ideas,
			s.vote_count
		FROM statistics_recap s
		WHERE s.at >= $1;

-- name: StatisticsRepositoryIdeasRecap1 :one
SELECT
			COUNT(*) FILTER (WHERE state = 'waiting')  AS waiting,
			COUNT(*) FILTER (WHERE state = 'approved') AS approved,
			COUNT(*) FILTER (WHERE state = 'declined') AS declined
		FROM submissions;

-- name: StatisticsRepositoryQualityRecap1 :one
SELECT
		    COUNT (*) FILTER (WHERE rate = 'good') AS good,
		    COUNT (*) FILTER (WHERE rate = 'bad') AS bad
		FROM pictures;

-- name: SubmissionsRepositoryGetList1 :many
SELECT s.id, s.project_id, s.state, s.reason FROM submissions s;

-- name: SubmissionsRepositoryGetByID1 :one
SELECT s.project_id, s.state, s.reason FROM submissions s WHERE s.id = $1;

-- name: SubmissionsRepositoryAlreadySetted1 :one
SELECT EXISTS (SELECT 1 FROM submissions WHERE id = $1 AND state <> 'waiting');

-- name: SubmissionsRepositoryApprove1 :exec
WITH upd AS (
			UPDATE submissions
			SET state = 'approved'
			WHERE submissions.id = $1
			RETURNING project_id
		)
		UPDATE projects
		SET status = 'published'
		WHERE projects.id = (SELECT upd.project_id FROM upd);

-- name: SubmissionsRepositoryDecline1 :exec
UPDATE submissions SET state = 'declined', reason = $1 WHERE id = $2;

-- name: VerificationRepositoryCreate1 :exec
INSERT INTO auth_action_tokens (email, purpose, token_hash, expires_at, ip, user_agent, created_at)
		VALUES ($1, $2, $3, $4, $5, $6, $7)
		ON CONFLICT (email, purpose) WHERE used_at IS NULL
		DO UPDATE SET
			token_hash = EXCLUDED.token_hash,
			expires_at = EXCLUDED.expires_at,
			ip = EXCLUDED.ip,
			user_agent = EXCLUDED.user_agent,
			created_at = EXCLUDED.created_at,
			used_at = NULL;

-- name: VerificationRepositoryGetRecord1 :one
SELECT id, email, purpose, expires_at, used_at FROM auth_action_tokens WHERE token_hash = $1 AND purpose = $2;

-- name: VerificationRepositoryConsume1 :exec
UPDATE auth_action_tokens SET used_at = $1 WHERE token_hash = $2 AND purpose = $3 AND used_at IS NULL;

-- name: VerificationRepositoryBanEmail1 :exec
INSERT INTO banned_emails (email, reason) VALUES ($1, $2);

-- name: VerificationRepositoryIsBanned1 :one
SELECT EXISTS (SELECT 1 FROM banned_emails WHERE email = $1);

-- name: VerificationRepositoryEmailExists1 :one
SELECT EXISTS (SELECT 1 FROM users WHERE (email).address = $1);

-- name: MaintenanceRepositoryCheckIsActive1 :one
SELECT EXISTS (SELECT 1 FROM maintenance m WHERE m.status = 'in progress');

-- name: MaintenanceRepositorySetActive1 :exec
UPDATE maintenance SET status = 'in progress', actual_start_at = $1 WHERE id = $2;

-- name: MaintenanceRepositoryIsPlanned1 :one
SELECT EXISTS (SELECT 1 FROM maintenance m WHERE m.status = 'scheduled');

-- name: MaintenanceRepositoryGetData1 :one
SELECT m.* FROM maintenance m WHERE m.status = 'in progress';

-- name: MaintenanceRepositoryStart1 :exec
INSERT INTO maintenance (description, scope, type, planned_start_at, planned_end_at, called_by) VALUES ($1, $2, $3, $4, $5, $6);

-- name: MaintenanceRepositoryEdit1 :exec
UPDATE maintenance SET description = $1 WHERE status = 'in progress';

-- name: MaintenanceRepositoryEdit2 :exec
UPDATE maintenance SET scope = $1 WHERE status = 'in progress';

-- name: MaintenanceRepositoryComplete1 :exec
UPDATE maintenance SET status = 'completed', actual_end_at = $1 WHERE status = 'in progress';

-- name: MaintenanceRepositoryGetList1 :many
SELECT * FROM maintenance;

-- name: TicketsRepositoryCreate1 :one
INSERT INTO tickets (name, email, topic, brief, authorized_uid, authorized) VALUES ($1, $2, $3, $4, $5, true) RETURNING id;

-- name: TicketsRepositoryCreate2 :one
INSERT INTO tickets (name, email, topic, brief, requestor_token) VALUES ($1, $2, $3, $4, $5) RETURNING id;

-- name: TicketsRepositoryCreate3 :exec
INSERT INTO ticket_messages (ticket, author_type, content) VALUES ($1, $2, $3);

-- name: TicketsRepositoryCreateMessage1 :exec
INSERT INTO ticket_messages (ticket, author_uid, author_name, author_email, author_type, content) VALUES ($1, $2, $3, $4, $5, $6);

-- name: TicketsRepositoryCreateMessage2 :exec
INSERT INTO ticket_messages (ticket, author_name, author_email, author_type, content) VALUES ($1, $2, $3, $4, $5);

-- name: TicketsRepositoryAccepted1 :one
SELECT status = 'в обработке' FROM tickets WHERE id = $1;

-- name: TicketsRepositoryAccept1 :exec
UPDATE tickets SET acceptor = $1, accepted = $2, status = $3 WHERE id = $4 AND status <> $3;

-- name: TicketsRepositoryAccept2 :one
SELECT acceptor FROM tickets WHERE id = $1;

-- name: TicketsRepositoryInfo1 :one
SELECT t.* FROM tickets t WHERE t.id = $1;

-- name: TicketsRepositoryEditMessage1 :exec
UPDATE ticket_messages SET content = $1, edited_at = NOW() WHERE ticket = $2 AND id = $3 AND deleted_at IS NULL;

-- name: TicketsRepositoryDeleteMessage1 :exec
UPDATE ticket_messages SET deleted_at = NOW(), deleted_by = $1 WHERE ticket = $2 AND id = $3 AND deleted_at IS NULL;

-- name: TicketsRepositoryGetLatestMessage1 :one
SELECT
			m.id,
			m.ticket,
			m.author_type,
			m.author_uid,
			m.author_name,
			m.author_email,
			m.content,
			m.at,
			m.edited_at,
			m.deleted_at,
			m.deleted_by
		FROM ticket_messages m
		WHERE m.ticket = $1
		ORDER BY m.at DESC, m.id DESC
		LIMIT 1;

-- name: TicketsRepositoryIsReqValid1 :one
SELECT EXISTS (SELECT 1 FROM tickets WHERE requestor_token = $1 AND id = $2);

-- name: TicketsRepositoryIsReqValid2 :one
SELECT EXISTS (SELECT 1 FROM tickets WHERE authorized_uid = $1 AND id = $2);

-- name: TicketsRepositoryClose1 :exec
UPDATE tickets SET closed = NOW(), closed_by = $1, close_reason = $2, status = $3 WHERE id = $4;

-- name: TicketsRepositoryIsClosed1 :one
SELECT status = 'закрыт' FROM tickets WHERE id = $1;

-- name: TicketsRepositoryUser1 :one
SELECT name, email FROM tickets WHERE requestor_token = $1;

-- name: TicketsRepositoryUser2 :one
SELECT name, email FROM tickets WHERE authorized_uid = $1;

-- name: TicketsRepositoryLatestAt1 :one
SELECT at FROM ticket_messages WHERE ticket = $1 ORDER BY at DESC LIMIT 1;

-- name: RanksRepositoryList1 :many
SELECT r.name, r.color, r.description, r.weight, r.permissions, r.added_at FROM ranks r ORDER BY r.added_at DESC;

-- name: RanksRepositoryUsersWithRank1 :many
SELECT u.uid FROM users u WHERE (u.rank).name = $1;

-- name: RanksRepositoryPerms1 :one
SELECT to_jsonb(r.permissions) FROM ranks r WHERE r.name = $1;

-- name: RanksRepositoryChangePerms1 :exec
UPDATE ranks r
		 SET permissions = perm_set(r.permissions, $1, $2)
		 WHERE r.name = $3;

-- name: RanksRepositoryCreate1 :exec
INSERT INTO ranks (name, color, description, permissions)
			VALUES ($1, $2, $3, jsonb_populate_record(null::permissions_t, $4::jsonb));

-- name: RanksRepositoryCreate2 :exec
INSERT INTO ranks (name, color, description) VALUES ($1, $2, $3);

-- name: RanksRepositoryIsExists1 :one
SELECT EXISTS (SELECT 1 FROM ranks WHERE name = $1);

-- name: RanksRepositoryGet1 :one
SELECT color, description, added_at FROM ranks WHERE name = $1;

-- name: RanksRepositoryDelete1 :exec
DELETE FROM ranks WHERE name = $1;

-- name: RanksRepositoryCanEdit1 :one
SELECT COALESCE(r1.weight, 0) > COALESCE(r2.weight, 0) AS can_edit FROM (SELECT ranks.weight FROM ranks WHERE ranks.name = $1) r1 CROSS JOIN (SELECT ranks.weight FROM ranks WHERE ranks.name = $2) r2;

-- name: RanksRepositoryCreateActivations1 :exec
INSERT INTO rank_activations (code, rank) VALUES ($1, $2);

-- name: NotificationsRepositoryGetAll1 :many
SELECT id, body, createdAt, scope, targetUserID, targetSegment, expiresAt FROM notifications ORDER BY createdAt DESC;

-- name: NotificationsRepositoryInsertNotification1 :one
INSERT INTO notifications (body, scope, targetUserID, targetSegment, expiresAt) VALUES ($1, $2, $3, $4, $5) RETURNING id;

-- name: NotificationsRepositoryMark1 :exec
INSERT INTO notification_receipts (notify_id, userID, readAt)
		 VALUES ($1, $2, now())
		 ON CONFLICT (notify_id, userID)
		 DO UPDATE SET readAt = EXCLUDED.readAt;

-- name: UserRepositorySetRank1 :exec
UPDATE users SET rank = ROW($1, NULL)::users_rank_t WHERE uid = $2;

-- name: UserRepositorySetRank2 :exec
UPDATE users SET rank = ROW($1, $2)::users_rank_t WHERE uid = $3;

-- name: TicketsRepositoryList1 :many
SELECT t.* FROM tickets t ORDER BY t.created DESC;

-- name: TicketsRepositoryList2 :many
SELECT t.* FROM tickets t WHERE t.authorized = $1 AND t.authorized_uid = $2 ORDER BY t.created DESC;

-- name: TicketsRepositoryList3 :many
SELECT t.* FROM tickets t WHERE t.authorized = $1 AND t.requestor_token = $2 ORDER BY t.created DESC;

-- name: NotificationsRepositoryForUser1 :many
SELECT n.id, n.body, n.createdAt, n.scope, n.expiresAt, nr.readAt
FROM notifications n
LEFT JOIN notification_receipts nr
  ON nr.notify_id = n.id AND nr.userID = $1
WHERE
  (n.expiresAt IS NULL OR n.expiresAt > now())
  AND (
    n.scope = 'broadcast'
    OR (n.scope = 'user' AND n.targetUserID = $1)
    OR (n.scope = 'segment' AND n.targetSegment = $2)
  )
  AND ($3::bool OR nr.readAt IS NULL)
ORDER BY n.createdAt DESC;
